### ISSUE TITLE
build.yaml specifying path of files to run moor_generator on

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#1001]
i'm seeing moor_generator:moor_generator on lib/bottomSheets/... .dart  (one of my widgets)

how can i limit moor_generator to only run lib\db ? i tried to see about this on https://moor.simonbinder.eu/docs/advanced-features/builder_options/

i saw one place online about build.yaml and a:
targets:
  $default:
    sources:
      include: ["**"]

but, it's not clear to me how to specify path of files to run moor_generator on. thanks,

**Comment by simolus3** [comment]
If you're running `moor_generator` in your default target (you probably are), you can limit the inputs of `moor_generator` like this:

```yaml
targets:
  $default:
    builders:
      moor_generator|moor_generator:
        generate_for: ["lib/db/**"]
```

Setting the sources of the default target would be another option, but that affects other builders (like `json_serializable` or `built_value`) as well.

Also, feel free to ask questions like this in the [discussions](https://github.com/simolus3/moor/discussions) :)
