### ISSUE TITLE
Moor_generator ^3.4.0 is incompatible with integration_test from sdk

### ISSUE THREAD

**Issue by tatosjb** [simolus3/moor#1003]
Running "flutter pub get" in stock_counter...                   
Because no versions of moor_generator match >3.4.0 <4.0.0 and moor_generator 3.4.0 depends on cli_util ^0.1.0, moor_generator ^3.4.0 requires cli_util ^0.1.0.

And because every version of integration_test from sdk depends on cli_util 0.2.0, moor_generator ^3.4.0 is incompatible with integration_test from sdk.

So, because stock_counter depends on both integration_test any from sdk and moor_generator ^3.4.0, version solving failed.
pub get failed (1; So, because stock_counter depends on both integration_test any from sdk and moor_generator ^3.4.0, version solving failed.)
exit code 1

```yml
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.2.8
  cupertino_icons: ^1.0.2
  provider: ^4.3.2+4
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  moor_generator: ^3.4.0
  build_runner:

flutter:
  uses-material-design: true
```
