### ISSUE TITLE
The rank column from fts5 extension is not of integer type

### ISSUE THREAD

**Issue by krigga** [simolus3/moor#1066]
I wrote the following query: 
```
SELECT * FROM table_name LEFT JOIN (SELECT rowid AS search_rowid, rank AS search_rank FROM table_name_search WHERE table_name_search MATCH ?) ON table_name.id = search_rowid ORDER BY search_rank DESC
```
where table_name_search is an fts5 table.
I started getting `FormatException: Invalid radix-10 number`, followed by numbers like `-0.0123`, on any attempts of getting data from that query. Replacing `searchRank: row.readInt('search_rank'),` with `searchRank: 0,` in the generated code fixed the exceptions, and since I don't really care about that rank for any reason other than sorting I can move on, but I think this needs to be fixed. I guess the problem is here:
https://github.com/simolus3/moor/blob/c7e7683edecdf3dff4f19422cc019b6e9fdc691f/sqlparser/lib/src/engine/module/fts5.dart#L167
but I don't actually know.
pubspec.lock:
```
  moor:
    dependency: "direct main"
    description:
      name: moor
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.0"
  moor_generator:
    dependency: "direct dev"
    description:
      name: moor_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.1"
  sqlite3:
    dependency: transitive
    description:
      name: sqlite3
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.8"
  sqlite3_flutter_libs:
    dependency: "direct main"
    description:
      name: sqlite3_flutter_libs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0"
  sqlparser:
    dependency: transitive
    description:
      name: sqlparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.0"
```
