### ISSUE TITLE
Analyzer dependencies conflicts

### ISSUE THREAD

**Issue by MiguelSOliveira** [simolus3/moor#1077]
In moor_generator (and maybe others), there's the following dependency: `analyzer: ">=0.40.0 <0.43.0"`.

This has conflicts when upgrading other packages to null safety because they depend on `analyzer: ^1.1.0`.

**Comment by simolus3** [comment]
Yes, unfortunately we also depend on `analyzer_plugin` which doesn't support the latest analyzer yet (well, it does, it's just published very infrequently).

I've applied a workaround for that in d279f1cdffeb48235db6be41f6adf756af96f6f0.

**Comment by tony123S** [comment]
How to fix ? I don't understand how to apply it

**Comment by MiguelSOliveira** [comment]
@tony123S 

```
moor_generator:
    git:
      url: git@github.com:simolus3/moor.git
      path: moor_generator
      ref: d279f1cdffeb48235db6be41f6adf756af96f6f0
```

**Comment by tony123S** [comment]
@MiguelSOliveira 

```
Git error. Command: `git clone --mirror git@github.com:simolus3/moor.git /home/xxx/Desktop/flutter_linux_1.22.6-stable/flutter/.pub-cache/git/cache/moor-f3c1a9b90345ae935196e3531c15f1a51bfef385`

stdout: 

stderr: Cloning into bare repository '/home/xxx/Desktop/flutter_linux_1.22.6-stable/flutter/.pub-cache/git/cache/moor-f3c1a9b90345ae935196e3531c15f1a51bfef385'...

git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

exit code: 128
```

**Comment by simolus3** [comment]
@tony123S Try using https instead of ssh:

```yaml
  moor_generator:
    git:
      url: https://github.com/simolus3/moor.git
      ref: d279f1cdffeb48235db6be41f6adf756af96f6f0
      path: moor_generator
```
