### ISSUE TITLE
Unhandled Exception: SqliteException(1): index activities_index already exists

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#1084]
I am already using indexes in a while with .moor files and in it, I have a long list of indexes which the first is:

`CREATE INDEX activities_index ON activities(uid);`

I often use migrations to bump the database scheme, but none of them affected this table and I didn't have any problems with the changes.

But now, and for a while, I got this error every time I open the app:

```
E/flutter ( 5822): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SqliteException(1): index activities_index already exists
E/flutter ( 5822): #0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:110:7)
E/flutter ( 5822): #1      _VmDelegate._runWithArgs (package:moor/src/ffi/vm_database.dart:160:11)
E/flutter ( 5822): #2      _VmDelegate.runCustom (package:moor/src/ffi/vm_database.dart:170:11)
E/flutter ( 5822): #3      _ExecutorWithQueryDelegate.runCustom.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:79:19)
E/flutter ( 5822): #4      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:25:26)
E/flutter ( 5822): #5      _ExecutorWithQueryDelegate.runCustom (package:moor/src/runtime/executor/helpers/engines.dart:76:12)
E/flutter ( 5822): #6      QueryEngine.customStatement.<anonymous closure> (package:moor/src/runtime/api/query_engine.dart:301:23)
E/flutter ( 5822): #7      QueryEngine.doWhenOpened.<anonymous closure> (package:moor/src/runtime/api/query_engine.dart:98:64)
E/flutter ( 5822): #8      _rootRunUnary (dart:async/zone.dart:1194:47)
E/flutter ( 5822): #9      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
E/flutter ( 5822): #10     _FutureListener.handleValue (dart:async/future_impl.dart:150:18)
E/flutter ( 5822): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:703:45)
E/flutter ( 5822): #12     Future._propagateToListeners (dart:async/future_impl.dart:732:32)
E/flutter ( 5822): #13     Future._completeWithValue (dart:async/future_impl.dart:536:5)
E/flutter ( 5822): #14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:574:7)
E/flutter ( 5822): #15     _rootRun (dart:async/zone.dart:1186:13)
E/flutter ( 5822): #16     _CustomZone.run (dart:async/zone.dart:1090:19)
E/flutter ( 5822): #17     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
E/flutter ( 5822): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
E/flutter ( 5822): #19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5822): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

It happens even when I create the database for the first time!

In one of my migrations, I dropped and recreated a table, but it was long ago and I am not sure if the error started at that time.

I use:

```
  sqflite_sqlcipher: ^1.0.0+6
  moor:
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
      ref: 348fb655cefb1ee777c76935cdb0c873886c393e

  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs
  sqflite: ^1.1.7

dev_dependencies:
  moor_generator:
  build_runner:
```

Any suggestions? Thank you! : )
