### ISSUE TITLE
The function 'VmDatabase isn't defined on moor_flutter ^3.1.0

### ISSUE THREAD

**Issue by tazik561** [simolus3/moor#1107]
I am trying to make Integrated testing on moor so I installed :

```
 environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  moor_flutter: ^3.1.0
  path_provider: ^2.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: null
  build_runner: null
```
In database class I am trying to create database :

```
import 'dart:io';
import 'package:moor_flutter/moor_flutter.dart';
import 'package:moor_testing/user_dao.dart';
import 'package:moor_testing/user_tb.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'package:moor/ffi.dart';
part 'database.g.dart';

LazyDatabase openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return VmDatabase(file);
  });
}

@UseMoor(tables: [
  UserTables,
], daos: [
  UserDao,
])
class Database extends _$Database {
  Database()
      : super(openConnection());

  @override
  int get schemaVersion => 1;
}
```

But in the `return VmDatabase(file);` I got : The function 'VmDatabase isn't defined ?

https://pasteboard.co/JT5apbo.png

This is doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

These are downloaded in `/.pub-cache/hosted/pub.dartlang.org`
```
Alt@mx:~/.pub-cache/hosted/pub.dartlang.org
$ ls -l | grep "moor"
drwxr-xr-x  6 Alt Alt 4096 Mar 18 00:08 moor-3.2.0
drwxr-xr-x  6 Alt Alt 4096 Mar 17 23:49 moor-3.4.0
drwxr-xr-x  5 Alt Alt 4096 Mar 17 23:47 moor_flutter-3.1.0
drwxr-xr-x  5 Alt Alt 4096 Mar 17 23:47 moor_generator-3.4.1
```
