### ISSUE TITLE
Perhaps a tiny bug: moor_generator fails if the dart file contains "import 'package:flutter/material.dart';"

### ISSUE THREAD

**Issue by Guoyuer** [simolus3/moor#1144]
base.dart:
```
import 'package:moor_flutter/moor_flutter.dart';
import 'package:flutter/material.dart';

part 'base.g.dart';

class Events extends Table {
  IntColumn get id => integer().autoIncrement()();

  RealColumn get sumVal => real().withDefault(Constant(0))();
}

class Records extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get eventId => integer()();

  RealColumn get value => real().nullable()();
}

class Units extends Table {
  IntColumn get id => integer().autoIncrement()();
}

@UseMoor(tables: [Units, Records, Events])
class AppDatabase extends _$AppDatabase {
  AppDatabase()
      : super(FlutterQueryExecutor.inDatabaseFolder(
            path: "db.sqlite", logStatements: true));

  @override
  int get schemaVersion => 2;
}

```

The generation would be: 
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'base.dart';

// **************************************************************************
// MoorGenerator
// **************************************************************************

// ignore_for_file: unnecessary_brace_in_string_interps, unnecessary_this
abstract class _$AppDatabase extends GeneratedDatabase {
  _$AppDatabase(QueryExecutor e) : super(SqlTypeSystem.defaultInstance, e);
  @override
  Iterable<TableInfo> get allTables => allSchemaEntities.whereType<TableInfo>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [];
}

``` 
which contains no tables.

pubspec.yaml:
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor_flutter:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator:
```
**However, removing the "import material.dart" line can solve this problem.**
