### ISSUE TITLE
TRIGGER with RAISE keyword issue while running build runner

### ISSUE THREAD

**Issue by developer-zh** [simolus3/moor#1154]
First off, thank you for this really helpful package.

After completing my `.moor` file, I tried running the builder and encountered the following issue:
```
Could not parse this expression. Note: This is a reserved keyword, you can escape it in double ticks
RAISE (ABORT, "Attempting to add a parent category that does not exist")
^^^^^
```
For a better context, here is my the whole trigger definition
```
CREATE TRIGGER categories_bi BEFORE INSERT ON categories
BEGIN
    SELECT
        CASE WHEN new.is_top_level < 1 THEN
	    CASE WHEN NOT EXISTS (SELECT id FROM categories WHERE id = new.parent_id) THEN
		RAISE (ABORT, "Attempting to add a parent category that does not exist")
	    END
        END;
END;
```
Tried wrapping the `RAISE` and inner `CASE` statement with parenthesis but the runner still throws the issue.

I might be missing something, as SQL is not my most strongest suite. Could you provide some clue on how to go about this? Many thanks!

**Comment by simolus3** [comment]
I think `RAISE` is not yet supported by the sql parser used in the generator. It shouldn't take much to implement it, I'll take a look at that now.

**Comment by simolus3** [comment]
This should be fixed now. If you want to try it out before the next update, you can temporarily add this to your pubspec:

```yaml
dependency_overrides:
  moor_generator:
    git:
      url: https://github.com/simolus3/moor.git
      ref: 17f43bc9fc192510f3bc62893c219e92d6c0332a
      path: moor_generator
  sqlparser:
    git:
      url: https://github.com/simolus3/moor.git
      ref: 17f43bc9fc192510f3bc62893c219e92d6c0332a
      path: sqlparser
```
