### ISSUE TITLE
Can not use Isolate with Encrypted version of moor/ffi

### ISSUE THREAD

**Issue by k3vinb0ss** [simolus3/moor#1286]
Hi, I'm using the encrypted version of moor/ffi to encrypt my database, using fts5 extension too. The problem is when i'm trying to write records into database it drop my frames (ffi ? ), thus i apply this [Moor Background Isolate](https://moor.simonbinder.eu/docs/advanced-features/isolates/ ).  But it failed to override **libsqlite3.so** with **libsqlcipher.so** like below:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '/data/data/com.aganticsoft.si/lib/libsqlite3.so': dlopen failed: library "/data/data/com.aganticsoft.si/lib/libsqlite3.so" not found
E/flutter (23825): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter (23825): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter (23825): #2      _defaultOpen (package:sqlite3/src/load_library.dart:40:31)
E/flutter (23825): #3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/load_library.dart:122:12)
E/flutter (23825): #4      sqlite3 (package:sqlite3/src/api/sqlite3.dart:12:38)
E/flutter (23825): #5      _VmDelegate._createDatabase (package:moor/src/ffi/vm_database.dart:159:13)
E/flutter (23825): #6      _VmDelegate.open (package:moor/src/ffi/vm_database.dart:138:7)
E/flutter (23825): #7      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:259:22)
E/flutter (23825): <asynchronous suspension>
E/flutter (23825): #8      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
E/flutter (23825): <asynchronous suspension>
E/flutter (23825): #9      ServerImplementation._handleEnsureOpen (package:moor/src/runtime/remote/server_impl.dart:117:12)
E/flutter (23825): <asynchronous suspension>
E/flutter (23825): #10     MoorCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/remote/communication.dart)
E/flutter (23825): <asynchronous suspension>
```

And here is my implementation:

```yaml
# build.yaml
targets:
  $default:
    builders:
      moor_generator:
        options:
          compact_query_methods: true
          sqlite:
            modules:
              - fts5
              - moor_ffi
```

```yaml
#pubspec.yaml
  moor: ^4.3.2
  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs
```

```dart
static void setupSqlcipher() {
    open.overrideFor(
        OperatingSystem.android, () => DynamicLibrary.open('libsqlcipher.so'));
}



Future<AppDatabase> injectDatabaseV2() async {
  MoorIsolate moorIsolate = await createMoorIsolate();
  AppDatabase.setupSqlcipher();
  final connection = await moorIsolate.connect();
  final db = AppDatabase.connect(connection);

  return db;
}

Future<MoorIsolate> createMoorIsolate() async {
  final dir = await getApplicationDocumentsDirectory();
  final receivePort = ReceivePort();

  await Isolate.spawn(
    _startBackground,
    _IsolateStartRequest(receivePort.sendPort, dir.path),
  );

  return (await receivePort.first as MoorIsolate);
}

void _startBackground(_IsolateStartRequest request) {

  final dbFile = File(path.join(request.targetPath, 'newOne.sqlite'));
  final executor = VmDatabase(dbFile, setup: (rawDb) {
    rawDb.execute("PRAGMA key = '123456';");
  });
  final moorIsolate = MoorIsolate.inCurrent(
        () => DatabaseConnection.fromExecutor(executor),
  );
  request.sendMoorIsolate.send(moorIsolate);
}

class _IsolateStartRequest {
  final SendPort sendMoorIsolate;
  final String targetPath;

  _IsolateStartRequest(this.sendMoorIsolate, this.targetPath);
}

```
