### ISSUE TITLE
Target of URI doesn't exist: 'package:moor/ffi.dart'

### ISSUE THREAD

**Issue by doomkin** [simolus3/moor#1300]
After the update **moor** to 3.2.0 IntellyJ IDEA 2021.1 does not see `moor/ffi.dart`

```
import 'package:moor/moor.dart'; // exists
import 'package:moor/ffi.dart';  // not exists
```

Because of this, the error: The function 'VmDatabase' isn't defined.

`pubspec.yaml`
```
dependencies:
  sqflite:
  moor:
  sqlite3_flutter_libs:
```
Performed:
```
rm -R ~/.pub-cache
flutter clean
flutter pub get
```
