### ISSUE TITLE
moor 4.5.0 is incompatible with Flutter stable (2.2.3)

### ISSUE THREAD

**Issue by PiN73** [simolus3/moor#1429]
```
% flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

```yaml
name: hello

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  moor_generator: ^4.5.0
```

```
% flutter pub get
Running "flutter pub get" in hello...

Because no versions of moor_generator match >4.5.0 <5.0.0 and moor_generator 4.5.0 depends on analyzer ^2.1.0, moor_generator ^4.5.0 requires analyzer ^2.1.0.
And because analyzer >=2.0.0 depends on meta ^1.7.0 and every version of flutter from sdk depends on meta 1.3.0, moor_generator ^4.5.0 is incompatible with flutter from sdk.
So, because hello depends on both flutter any from sdk and moor_generator ^4.5.0, version solving failed.
pub get failed (1; So, because hello depends on both flutter any from sdk and moor_generator ^4.5.0, version solving failed.)
Process finished with exit code 1
```

It seems the problem is caused by `analyzer` and `json_annotation` dependencies
