### ISSUE TITLE
BlobColumn generation for custom row class: Parameter must accept List<int>

### ISSUE THREAD

**Issue by edwardaux** [simolus3/moor#1453]
I'm using a custom row class like this:
```
@UseRowClass(MyObject)
class MyObjects extends Table {
  BlobColumn get someData => blob()();
}

class MyObject {
  final Uint8List someData;
  MyObject({required this.someData});
}
```
However, when I run the generator, I get this error message from the generator complaining about my `MyObject` constructor:
> Parameter must accept `List<int>` 

If I contrast this to how it works for a standard `Table` subclass:
```
class MyObjects extends Table {
  BlobColumn get someData => blob()();
}
```
The generated code uses `Uint8List` and looks something like this (which is basically the same):
```
class MyObject extends DataClass implements Insertable<MyObject> {
  final Uint8List someData;
  MyObject({required this.someData});
  ...
}
```

Looking at the generated code, it actually generates the same code for both cases - which is good. But I'd like to get rid of the warnings that are polluting my generation phase because they have the potential to hide other actual errors.

I don't suppose there's a way to suppress this warning, is there?

moor: ^4.5.0
moor_generator: ^4.5.1

**Comment by simolus3** [comment]
Thanks for the report! This was mostly a technical limitation because it's hard to check whether something is a `Uint8List` with the analyzer. I applied a workaround in cc7d98d110204acb72d415312a78ed7821382d69, which fixes the problem.

**Comment by edwardaux** [comment]
Wow. Thanks for the quick turnaround. I had a quick attempt at getting it to work by adding this to my `pubspec.yaml`:
```
  moor_generator:
    git:
      url: git@github.com:simolus3/moor.git
      ref: cc7d98d110204acb72d415312a78ed7821382d69
```
However, when I run the generator, I get a bunch of errors that look like:
```
[WARNING] ../../flutter/.pub-cache/hosted/pub.dartlang.org/source_gen-1.0.3/lib/src/utils.dart:46:39: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
  if (element.name != null && element.name!.isNotEmpty) {
                                      ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/source_gen-1.0.3/lib/src/utils.dart:48:20: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
    return element.name!;
                   ^
../../flutter/.pub-cache/git/moor-efcd9bfa8381ba5c217d9a0140225436986ecd7c/moor_generator/lib/src/model/sql_query.dart:54:24: Error: 'TransactionBlock' isn't a type.
    } else if (stmt is TransactionBlock) {
                       ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/git/moor-efcd9bfa8381ba5c217d9a0140225436986ecd7c/moor_generator/lib/src/writer/queries/sql_writer.dart:95:30: Error: Type 'MoorSpecificNode' not found.
  void visitMoorSpecificNode(MoorSpecificNode e, void arg) {
                             ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/git/moor-efcd9bfa8381ba5c217d9a0140225436986ecd7c/moor_generator/lib/src/writer/queries/sql_writer.dart:95:30: Error: 'MoorSpecificNode' isn't a type.
  void visitMoorSpecificNode(MoorSpecificNode e, void arg) {
                             ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/git/moor-efcd9bfa8381ba5c217d9a0140225436986ecd7c/moor_generator/lib/src/writer/queries/sql_writer.dart:99:22: Error: Superclass has no method named 'visitMoorSpecificNode'.
        return super.visitMoorSpecificNode(e, arg);
```
I can see that you've been doing some recent work on these files... I had a couple of goes at trying to bash `pubspec.yaml` into submission, but after an hour I eventually gave up.

I'll just wait until the next published release of Moor 😂 Thanks again for a quick turnaround.

FWIW, looking at your fix, I noticed this line:
```
 type.element.name == 'Uint8List' &&
```
I wonder if this will indeed fix my specific problem... you see, in an attempt give a super-concise description of the problem, I omitted that I'm using `typedef Blob = Uint8List`, so my row class actually looks like:
```
class MyObject {
  final Blob someData;
  MyObject({required this.someData});
}
```
I'm not sure if the analyzer resolves those typedefs down into the real types when you ask for the name. Doing a bit of searching suggests that it might do (https://github.com/dart-lang/sdk/issues/33302), but I can't get moor generator to compile locally to test.

Anyway, thanks again for a great library.

**Comment by simolus3** [comment]
You'd have to add an override on the `sqlparser` package as well for this to work:

```yaml
  sqlparser:
    git:
      url: git@github.com:simolus3/moor.git
      ref: cc7d98d110204acb72d415312a78ed7821382d69
      path: sqlparser
```

Also, you make an excellent point about type aliases, but from an added test it appears to work :) The element's type is still reported as a regular `InterfaceType` pointing to `Uint8List`, it just has its `alias` set.

**Comment by edwardaux** [comment]
Ah, lovely. Thanks for confirming (and for the extra info).

Turns out, I was trying to add the overrides into the main `dev_dependencies` which doesn't work. The key is to use the `dependency_overrides` section. Anyway, in case anyone else happens to be watching, this is the exact config I'm using in my `pubspec.yaml`:

```
dependencies:
  ...
  moor: ^4.5.0

dev_dependencies:
  ...
  moor_generator: ^4.5.1

dependency_overrides:
  moor_generator:
    git:
      url: git@github.com:simolus3/moor.git
      ref: cc7d98d110204acb72d415312a78ed7821382d69
      path: moor_generator
  sqlparser:
    git:
      url: git@github.com:simolus3/moor.git
      ref: cc7d98d110204acb72d415312a78ed7821382d69
      path: sqlparser
```

Thanks again @simolus3 for such awesome support.
