### ISSUE TITLE
Failed when running "flutter packages pub run build_runner build --delete-conflicting-outputs" command after upgrading to 

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1477]
pubspec.yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter
  moor: ^4.5.0
  provider: ^5.0.0
  path_provider: any
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: any
  build_runner: any
  flutter_launcher_icons: any
```

Note: I use any in **pubspec.yaml**, because there were some conflicts even no code was changed after upgrading **Flutter** to **2.5.2**

I try to use **any** as version in **pubspec.yaml** for some packages with conflicts according to [this article](https://iiro.dev/resolving-dart-package-version-conflicts/)

My **Flutter** info:
```ruby
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (11 days ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3
```

Error as follow goes:
![image](https://user-images.githubusercontent.com/1920873/136885903-e7fc12ef-b27d-43a7-b026-8ebada6418cc.png)

**Comment by jims57** [comment]
I tried another solution.

a. Keeping the latest **Flutter** version as **2.5.2**, info about **Flutter** and **Dart** still like this:
```yaml
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (11 days ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3
```
b. Discarded all changes and reversed to the version of code before I upgraded **Flutter** to the latest version.
    Note: Before I upgraded **Flutter** version to **2.5.2**, everything run well, including the command I mentioned above, that is：
    `flutter packages pub run build_runner build --delete-conflicting-outputs`

The following is part of the content related to **Moor** in **pubspec.yaml:**
```yaml
dependencies:
  flutter:
    sdk: flutter
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  provider: ^5.0.0
  path_provider: ^1.3.0
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  moor_generator: ^3.4.0
```

But it shows another error as follows:
![image](https://user-images.githubusercontent.com/1920873/136895725-71b77ee5-bcd1-4d3e-8c9b-3d4715b4b6f0.png)

![image](https://user-images.githubusercontent.com/1920873/136895848-c9f3334c-bde2-49aa-bdd7-574f8ec81ba9.png)
