### ISSUE TITLE
Bug :( generateInsertable throws error when using it with freezed class

### ISSUE THREAD

**Issue by topperspal** [simolus3/moor#1587]
Constructor parameter id has no matching field. When "generateInsertable" enabled, all constructor parameter must have a matching field. Alternatively, you can declare a getter field.

**Comment by micimize** [comment]
With custom row classes, you have to make sure all fields in your data class constructor have a corresponding column in the table and vice-versa. If you can't find the discrepancy, paste actual data class and table snippets in code blocks

**Comment by topperspal** [comment]
> With custom row classes, you have to make sure all fields in your data class constructor have a corresponding column in the table and vice-versa. If you can't find the discrepancy, paste actual data class and table snippets in code blocks

```
@freezed
class User with _$User {
  const factory User({required int id}) = _User;
}
```

```
@UseRowClass(User, generateInsertable: true)
class Users extends Table {
  IntColumn get id => integer()();
}
```

This code produces the following error -

```
Constructor parameter id has no matching field. When "generateInsertable" enabled, all constructor parameter must have a matching field. Alternatively, you can declare a getter field.
   ╷
19 │   const factory User({required int id}) = _User;
```

**Comment by simolus3** [comment]
Thanks for the report! So I think there are two things going wrong here:

- Drift's generator expects the getter/field in the target class and does not consider inheritance - fixed in 36b23942f4a62c858f959fa824d10216bad196ca.
- You may have to tell Dart's build system to run freezed before drift so that the generator sees the `_$User` class with the getter. You can create a `build.yaml` file with this content (haven't tried it, but I think this should work)

```yaml
targets:
  freezed_only:
    auto_apply_builders: false
    builders:
      freezed:
        enabled: true
  $default:
    dependencies: [":freezed_only"]
    builders:
      freezed:
        enabled: false
```

**Comment by clragon** [comment]
I am somehow experiencing this again.

my build.yaml is looking like this:

```yaml
targets:
  freezed_only:
    auto_apply_builders: false
    builders:
      freezed:
        enabled: true
  $default:
    dependencies: [ ":freezed_only" ]
    builders:
      freezed:
        enabled: false
      json_serializable:
        options:
          field_rename: snake
      drift_dev:
        options:
          generate_connect_constructor: true
          use_data_class_name_for_companions: true
```

but during build I still get:
```
There were some errors while running moor_generator on package:e1547/history/data/database.dart:
[WARNING] drift_dev:drift_dev on lib/history/data/database.dart:
line 7, column 7 of package:e1547/history/data/entry.dart: This class used as a custom row class for which an insertable is generated. This means that it must define getters for all columns, but some are missing: host
  ╷
7 │ class History with _$History {
  │       ^^^^^^^
  ╵
```
