### ISSUE TITLE
Make it a breaking release if the generated files are getting changed.

### ISSUE THREAD

**Issue by xsahil03x** [simolus3/moor#1602]
We at [@Stream](https://github.com/GetStream) uses `drift` in one our package [stream_chat_persistence](https://github.com/GetStream/stream-chat-flutter/tree/master/packages/stream_chat_persistence). We were using [Caret Syntax](https://dart.dev/tools/pub/dependencies#caret-syntax) while using `drift` as a dependency.

```yaml
dependencies:
  drift: ^1.0.0
  
dev_dependencies:
  drift_dev: ^1.0.0
```

And due to the recent `v1.1.1` release of `drift` our users started facing this [issue](https://github.com/GetStream/stream-chat-flutter/issues/837) as the previously generated files no longer works with `v1.1.1` of `drift`.
