### ISSUE TITLE
Unable to use encrypted moor extension in a background isolate

### ISSUE THREAD

**Issue by Raluca1** [simolus3/moor#1705]
Hello,

I’ve been trying to use the encrypted moor extension:

```
drift: ^1.4.0
    encrypted_moor:
      git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
```

It’s working with database in main isolate. 

With database in a separate isolate, I get error:

> Cannot use this MethodChannel before the binary messenger has been initialized. This happens when you invoke platform methods before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().

Is it because of this issue: [Unable to call a platform channel method from another isolate](https://github.com/flutter/flutter/issues/13937)?

Is there a way to use encryption with the database in a background isolate? We are looking for solutions that work for iOS, Android and Web.

Thank you!
