### ISSUE TITLE
[BUG] drift_dev >=1.7.0 depends on analyzer_plugin ^0.10.0

### ISSUE THREAD

**Issue by zs-dima** [simolus3/moor#1935]
Could I kindly ask you to update dependencies?

```
Because drift_dev >=1.7.0 depends on analyzer_plugin ^0.10.0 and dart_code_metrics 4.17.0-dev.1 depends on analyzer_plugin ^0.11.0, drift_dev >=1.7.0 is incompatible with dart_code_metrics 4.17.0-dev.1.
And because no versions of dart_code_metrics match >4.17.0-dev.1 <5.0.0, drift_dev >=1.7.0 is incompatible with dart_code_metrics ^4.17.0-dev.1.
So, because app depends on both dart_code_metrics ^4.17.0-dev.1 and drift_dev ^1.7.0, version solving failed.
pub get failed (1; So, because app depends on both dart_code_metrics ^4.17.0-dev.1 and drift_dev ^1.7.0, version solving failed.)
exit code 1
```

**Comment by simolus3** [comment]
I have upgraded a while back (in commit 5317d0a33b5c66d20e8687743f8b7eb099dbd4c3), but this has not been released yet.

Would a git dpendency work for you?

```yaml
dependency_overrides:
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: 5317d0a33b5c66d20e8687743f8b7eb099dbd4c3
      path: drift_dev
```

I can look into cherry-picking this and releasing a hotfix if you need it urgently, but since it will be a bit of work I wonder if the dependency override alone works for you?
