### ISSUE TITLE
Schema tests failing in 2.0.0 on DateTime columns when store_as_text is true 

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#1992]
**Describe the bug**

I switched my columns in the drift files from `TEXT MAPPED BY 'MyCustomIsoDateTimeConverter()'` to `DATETIME` and set the `          store_date_time_values_as_text: true` flag.

I then regenerated and also generated the test schemas again, the offending columns now have the `DriftSqlType.dateTime` type.

All my columns that previously were correct, now cause a schema validation error.
```
  Schema does not match
  foo:
   columns:
    create_date:
     Different types: Expected INTEGER, got TEXT
```

It seems the schema comparison does not take the build flag into account.

**Comment by kuhnroyal** [comment]
Looks like the `SqlEngine` in `SchemaReader` and `FindSchemaDifferences` is constructed without the options.

**Comment by simolus3** [comment]
I don't think the `SqlEngine` is to blame here, it only compares the actual ASTs at runtime where there are no `DATETIME` types anymore.

> also generated the test schemas again

Just to be sure, the intention is still that previous schemas have datetime columns declared as text, right? Did you upgrade your schema version after making the switch and can `drift_dev schema dump` again?

Since the option might change, drift is now writing the current value of `store_date_time_values_as_text` into the serialized schema json (and lets that default to `false` if it's not there). `drift_dev schema generate` should ignore the current option from the `build.yaml` and only respect the one from the schema file. Could you check that the schema the failing test is targeting has `"options":{"store_date_time_values_as_text":true}` in its json?

**Comment by kuhnroyal** [comment]
Ok yea, so the builder option is set to `true` but the dumped schema contains:

```json
  "options": {
    "store_date_time_values_as_text": false
  },
```

I just ran the dump again with the same result.

**Comment by simolus3** [comment]
Do you apply the options on a non-default target? The current extraction logic in `drift_dev` is perhaps a bit to simplistic. Can you share the rough structure of your `build.yaml`?

**Comment by kuhnroyal** [comment]
Ahh yes! I have a separate goal and run built_value and other stuff beforehand.

```yaml
  drift:
    dependencies:
      - 'my_app'
    sources:
      - "lib/db/**"
      - "pubspec.yaml"
      - "pubspec.lock"
    auto_apply_builders: false
    builders:
      drift_dev|preparing_builder:
        enabled: true
      drift_dev|not_shared:
        enabled: true
        options:
          sql:
            dialect: sqlite
            options:
              version: "3.38"
          apply_converters_on_variables: true
          override_hash_and_equals_in_result_sets: true
          generate_connect_constructor: true
          scoped_dart_components: true
          named_parameters: true
          named_parameters_always_required: true
          use_data_class_name_for_companions: true
          generate_values_in_copy_with: true
          store_date_time_values_as_text: true
          skip_verification_code: true 
```
