### ISSUE TITLE
Drift 2.1.0 : Unrecognized keys: [compact_query_methods] when generate code

### ISSUE THREAD

**Issue by zgramming** [simolus3/moor#2036]
**Describe the bug**

Upgrade package from 1.7.1 to 2.1.0, then re-generate code using `flutter pub run build_runner build --delete-conflicting-outputs` then get error : 

```
PS C:\project_flutter\pik\idf_app_v2> flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 1.6s

[SEVERE]
CheckedFromJsonException
Could not create `DriftOptions`.
Unrecognized keys: [compact_query_methods]; supported keys: [write_from_json_string_constructor, override_hash_and_equals_in_result_sets, skip_verification_code, use_data_class_name_for_companions, use_column_name_as_json_key_when_defined_in_moor_file, generate_connect_constructor, sqlite_modules, sqlite, sql, data_class_to_companions, 
mutable_classes, raw_result_set_data, apply_converters_on_variables, generate_values_in_copy_with, named_parameters, named_parameters_always_required, scoped_dart_components, store_date_time_values_as_text]
pub finished with exit code 78
```

When I analyze the error, this error is directed at the build.yaml file. This is my `build.yaml` 

```
# build.yaml. This file is quite powerful, see https://pub.dev/packages/build_config

targets:
  $default:
    builders:
      drift_dev:
        options:
          compact_query_methods: true << this is the problem
          named_parameters: true
          named_parameters_always_required: true
```

Already see the changelog for breaking change for upgrade Version 1.X into [2.X](https://pub.dev/packages/drift/changelog#200) but the changelog not notice this, because when i generate in version 1.X is totally fine. And in documentation about [Builder Option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/) still in available options.

To solve problem, i comment the option `compact_query_methods`.
