### ISSUE TITLE
Drift can't resolve to the latest `analyzer` release

### ISSUE THREAD

**Issue by Carapacik** [simolus3/moor#2073]
After flutter pub get:

``` 
Because freezed >=2.1.1 depends on analyzer ^5.0.0 and drift_dev 2.1.0 depends on analyzer ^4.5.0, freezed >=2.1.1 is incompatible with drift_dev 2.1.0.
And because no versions of drift_dev match >2.1.0 <3.0.0, freezed >=2.1.1 is incompatible with drift_dev ^2.1.0.
So, because myproject depends on both drift_dev ^2.1.0 and freezed ^2.1.1, version solving failed.
pub get failed (1; So, because myproject  depends on both drift_dev ^2.1.0 and freezed ^2.1.1, version solving failed.)
A clear and concise description of what the bug is. Please briefly describe what behavior you expected, what behavior you saw, and how the bug can be reproduced. 
```

Maybe you should change the analyzer version from `"^4.5.0"` to `^4.5.0:`
https://github.com/simolus3/drift/blob/8c1a62ae1b65373d1403d80569b67cc959394d8b/drift_dev/pubspec.yaml#L33
You can also upgrade the analyzer to `^4.7.0`.

And after analyzer version 4.2.0 package support only on Dart higher than 2.17:
https://github.com/simolus3/drift/blob/8c1a62ae1b65373d1403d80569b67cc959394d8b/drift_dev/pubspec.yaml#L9

**Comment by Carapacik** [comment]
If you are busy, then I can open a PR with this fix.

**Comment by Carapacik** [comment]
My pubspec.yaml
```yaml
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  drift_dev: ^2.1.0
```
