### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by cimicdk** [simolus3/moor#2182]
When going to https://pub.dev/packages/drift/install it describes the installation process as:
` flutter pub add drift`

however, build_runner etc won't work until you add the dependencies as described here:
https://drift.simonbinder.eu/docs/getting-started/#adding-the-dependency

```
dependencies:
  drift: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

dev_dependencies:
  drift_dev: ^2.3.2
  build_runner: ^2.3.2

```

In my case, I ran ` flutter pub add drift`, went to your documentation, added table, database etc (which all compiles), but couldn't get the build_runner to work. As the compilation went fine, I didn't think about adding more dependencies.

Consider to add more information to pub.dev. Minimum add dev_dependencies so the build_runner works
```
dev_dependencies:
  drift_dev: ^2.3.2
```

Have a nice day :)
