### ISSUE TITLE
NoSuchMethodError: The method 'doWhenOpened' was called on null.

### ISSUE THREAD

**Issue by silverAndroid** [simolus3/moor#219]
**What I was trying to do**
Trying out `moor-ffi`, I followed the [guide](https://moor.simonbinder.eu/docs/other-engines/vm/) but it doesn't seem to be working as expected. I verified that this does work no problem on `moor-flutter`

**What is happening**
When I try and initialize the database, I see this in the logs
```dart
flutter: NoSuchMethodError: The method 'doWhenOpened' was called on null.
Receiver: null                                                          
Tried calling: doWhenOpened<List<Map<String, dynamic>>>(Closure: (QueryExecutor) => Future<List<Map<String, dynamic>>>)
```

db.dart:
```dart
import 'dart:io';

import 'package:moor/moor.dart';
import 'package:moor_ffi/moor_ffi.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

part 'db.g.dart';

@UseMoor(include: {'./db.moor'})
class Database extends _$Database {
  // we tell the database where to store the data with this constructor
  Database() : super(inDatabaseFolder(path: 'db.sqlite'));

  static inDatabaseFolder({String path}) {
    LazyDatabase(() async {
      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(p.join(dbFolder.path, path));
      return VmDatabase(file);
    });
  }

  // you should bump this number whenever you change or add a table definition. Migrations
  // are covered later in this readme.
  @override
  int get schemaVersion => 1;
}
```

db.moor
```sql
CREATE TABLE totp(
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  secret_key TEXT NOT NULL,
  image_url TEXT NOT NULL
);

getTotpList: SELECT id, name FROM totp;
getTotp: SELECT * FROM totp WHERE id = :id LIMIT 1;
addTotp: INSERT INTO totp (name, secret_key, image_url) VALUES (:name, :secret_key, :image_url);
```

pubspec.yaml (dependencies + devDependencies):
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bloc: ^0.14.0
  flutter_bloc: ^0.18.0
  equatable: ^0.2.0
  path: ^1.6.2
  otp: 1.0.3
  moor: ^2.0.0
  moor_ffi: 0.1.0-dev.1
  # moor_flutter: ^2.0.0
  path_provider: ^1.4.0
  path_provider_fde:
    path: ../flutter-desktop-embedding/plugins/flutter_plugins/path_provider_fde

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.0.0
  build_runner: ^1.7.2
```
