### ISSUE TITLE
Assertion failed: "unknown entity type Instance of 'DefinedSqlQuery'"

### ISSUE THREAD

**Issue by North101** [simolus3/moor#2194]
Error:
`flutter pub run drift_dev schema dump lib/db/database.dart db/schemas/ `
```
Unhandled exception:
Assertion failed: "unknown entity type Instance of 'DefinedSqlQuery'"
#0      SchemaWriter._entityToJson (package:drift_dev/src/services/schema/schema_files.dart:96:7)
#1      SchemaWriter.createSchemaJson (package:drift_dev/src/services/schema/schema_files.dart:35:40)
#2      DumpSchemaCommand.run (package:drift_dev/src/cli/commands/schema/dump.dart:88:57)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#4      MoorCli.run (package:drift_dev/src/cli/cli.dart:66:5)
<asynchronous suspension>
#5      run (package:drift_dev/src/cli/cli.dart:18:12)
<asynchronous suspension>
```

`build.yaml`
```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          named_parameters: true
          override_hash_and_equals_in_result_sets: true
          generate_connect_constructor: true
          store_date_time_values_as_text: true
      freezed:
        options:
          union_key: type
          union_value_key: snake
          explicit_to_json: true
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
```
