### ISSUE TITLE
Add Ignore Coverage for generated file

### ISSUE THREAD

**Issue by jarjut** [simolus3/moor#2225]
I'm building a project with coverage score. the generated file decrease the score. it would be nice if //coverage:ignore-file generated in each file. 

maybe make it look like this

``` dart
// coverage:ignore-file

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'class_dao.dart';
```

**Comment by simolus3** [comment]
You can actually do this with `source_gen`, which by default is responsible for merging code generated by different packages (like drift, built_value, json_serializable, ...) into a shared `.g.dart` file.

Create a `build.yaml` next to your `pubspec.yaml` and add the following content:

```yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          preamble: "// coverage:ignore-file"
```
