### ISSUE TITLE
Generated database file has error

### ISSUE THREAD

**Issue by HosseinArabbeigi** [simolus3/moor#225]
Hello

I'm trying to run moor document sample code and here is database code : 

```dart
import 'package:moor_flutter/moor_flutter.dart';

// assuming that your file is called filename.dart. This will give an error at first,
// but it's needed for moor to know about the generated code
part 'filename.g.dart';

// this will generate a table called "todos" for us. The rows of that table will
// be represented by a class called "Todo".
class Todos extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 6, max: 32)();
  TextColumn get content => text().named('body')();
  IntColumn get category => integer().nullable()();
}

// This will make moor generate a class called "Category" to represent a row in this table.
// By default, "Categorie" would have been used because it only strips away the trailing "s"
// in the table name.
@DataClassName("Category")
class Categories extends Table {

  IntColumn get id => integer().autoIncrement()();
  TextColumn get description => text()();
}

// this annotation tells moor to prepare a database class that uses both of the
// tables we just defined. We'll see how to use that database class in a moment.
@UseMoor(tables: [Todos, Categories])
class MyDatabase extends _$MyDatabase {
  // we tell the database where to store the data with this constructor
  MyDatabase() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite'));

  // you should bump this number whenever you change or add a table definition. Migrations
  // are covered later in this readme.
  @override
  int get schemaVersion => 1;
}

```
but generated file has error on this method:

```dart
@override
  T createCompanion<T extends UpdateCompanion<Todo>>(bool nullToAbsent)
```
 
error : 

> Todo.createCompanion' ('T Function<T extends UpdateCompanion<Todo>>(bool)') isn't a valid override of 'Insertable.createCompanion' ('createCompanion').

i cant understand whats wrong?

**Comment by simolus3** [comment]
Probably a version mismatch of `moor_generator` and `moor`. Can you try to `pub upgrade` and then re-run the build?

**Comment by HosseinArabbeigi** [comment]
Thanks for quick response.
doesn't work : 

```
  moor:
    dependency: transitive
    description:
      name: moor
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1+1"
  moor_flutter:
    dependency: "direct main"
    description:
      name: moor_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  moor_generator:
    dependency: "direct dev"
    description:
      name: moor_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
```
