### ISSUE TITLE
Suspecting drift not to be compatible with `fe_analyzer_shared:52.0.0` or `analyzer:5.4.0`

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/moor#2261]
**Describe the bug**

1. Run `flutter pub upgrade` -> flutter upgrades `_fe_analyzer_shared` to `52.0.0` and `analyzer` to `5.4.0`
2. Run `flutter pub run build_runner build --delete-conflicting-outputs` 
3. Following output is produced:

```
PS C:\FlutterProjects\mwork> flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 465ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 366ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 930ms

[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 16ms

[INFO] Generating build script...
[INFO] Generating build script completed, took 147ms

[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 9.6s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 918ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms

[INFO] Running build...
[INFO] 2.6s elapsed, 0/2 actions completed.
[INFO] 6.2s elapsed, 1/2 actions completed.
[INFO] Generating SDK summary...
[INFO] 9.4s elapsed, 2/18 actions completed.
[INFO] 11.4s elapsed, 2/18 actions completed.
[INFO] 12.5s elapsed, 2/18 actions completed.
[INFO] Generating SDK summary completed, took 6.3s

[SEVERE] chopper_generator on lib/services/drift/database/m_work_database.dart:

This builder requires Dart inputs without syntax errors.
However, package:mwork/services/drift/database/m_work_database.dart (or an existing part) contains the following errors.
m_work_database.dart:37:1: Expected a method, getter, setter or operator declaration.
m_work_database.dart:38:3: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
m_work_database.dart:38:3: Expected to find ';'.
And 11 more...

Try fixing the errors and re-running the build.

[INFO] 13.9s elapsed, 44/60 actions completed.
[INFO] 14.9s elapsed, 44/60 actions completed.
[INFO] 16.0s elapsed, 45/60 actions completed.
[INFO] 22.3s elapsed, 58/74 actions completed.
[INFO] 23.3s elapsed, 170/172 actions completed.
[INFO] 24.3s elapsed, 172/188 actions completed.
[INFO] 25.4s elapsed, 172/188 actions completed.
[INFO] 26.6s elapsed, 172/188 actions completed.
[INFO] 28.9s elapsed, 173/189 actions completed.
[INFO] 30.2s elapsed, 188/204 actions completed.
[WARNING] drift_dev on lib/services/drift/database/m_work_database.dart:
Could not resolve Dart library package:mwork/services/drift/database/m_work_database.dart
This builder requires Dart inputs without syntax errors.
However, package:mwork/services/drift/database/m_work_database.dart (or an existing part) contains the following errors.
m_work_database.dart:37:1: Expected a method, getter, setter or operator declaration.
m_work_database.dart:38:3: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
m_work_database.dart:38:3: Expected to find ';'.
And 11 more...

Try fixing the errors and re-running the build.

[INFO] 32.2s elapsed, 216/232 actions completed.
[INFO] 33.3s elapsed, 216/232 actions completed.
[INFO] 34.3s elapsed, 241/257 actions completed.
[INFO] 35.4s elapsed, 265/278 actions completed.
[INFO] 36.6s elapsed, 286/302 actions completed.
[INFO] 37.6s elapsed, 305/321 actions completed.
[INFO] 38.6s elapsed, 323/338 actions completed.
[INFO] 39.9s elapsed, 532/548 actions completed.
[SEVERE] json_serializable on lib/services/drift/database/m_work_database.dart:

This builder requires Dart inputs without syntax errors.
However, package:mwork/services/drift/database/m_work_database.dart (or an existing part) contains the following errors.
m_work_database.dart:37:1: Expected a method, getter, setter or operator declaration.
m_work_database.dart:38:3: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
m_work_database.dart:38:3: Expected to find ';'.
And 11 more...

Try fixing the errors and re-running the build.

[INFO] 41.6s elapsed, 606/621 actions completed.
[INFO] 42.6s elapsed, 633/648 actions completed.
[INFO] 43.7s elapsed, 656/671 actions completed.
[WARNING] json_serializable on lib/services/api/generated/mwork_api.swagger.dart:
Could not read the "pubspec.yaml` file associated with this package. Usage of package:json_annotation could not be verified.
[INFO] 45.6s elapsed, 849/849 actions completed.
[INFO] Running build completed, took 45.8s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 203ms

[SEVERE] Failed after 46.0s
pub finished with exit code 1

```
It seems that '*.g.dart' files aren't generated anymore.
![image](https://user-images.githubusercontent.com/11217296/211530601-46a56416-1883-43d8-8282-d870bad8acd3.png)

*Short term remedy*

4. Pin versions of `_fe_analyzer_shared` to `51.0.0` and `analyzer` to `5.3.1`
```
dependencies:
  _fe_analyzer_shared: 51.0.0
  analyzer: 5.3.1
```
5. Run 'flutter pub upgrade'

6. `flutter pub run build_runner build --delete-conflicting-outputs` runs smoothly again.

`pubspec.yaml`:
```
name: mwork
description: A tool for handling orders in Norva24.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+21

environment:
  sdk: ">=2.16.0-80.1.beta <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  _fe_analyzer_shared: 51.0.0
  analyzer: 5.3.1
  #camera_web: ^0.3.0
  #characters: ^1.2.1
  #material_color_utilities: ^0.1.5


  #flutter_webview_plugin:
  #  git: https://github.com/nuc134r/flutter_webview_plugin.git

  msal_js: ^2.14.0
  aad_oauth: ^0.4.1
  provider: ^6.0.3
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  #introduction_screen: ^3.0.2
  intl: ^0.18.0
  #socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter:
    sdk: flutter

  #--jwt--- makes it possible to analyze jwt

  jwt_decode: ^0.3.1

  #---Swagger changes---
  chopper: ^6.0.0
  json_annotation: ^4.5.0

  #---Google Maps---
  google_maps_flutter: ^2.1.7
  google_maps_flutter_web: ^0.4.0

  #---Location data (GPS)---
  #location: ^4.4.0
  location: ^5.0.0-dev.8

  #---Get---
  get: ^4.6.5

  #---Flutter Bloc---
  flutter_bloc: ^8.0.1

  #---Settings / preferences ---
  #flutter_settings_screens: ^0.3.2-null-safety
  pref: ^2.6.0

  #---Camera function---
  camera: ^0.10.0+1
  path_provider: ^2.0.11
  path: ^1.8.1

  #---Floor functionality---
  #floor: ^1.2.0

  #---Drift functionality---
  drift: ^2.3.0
  #drift:
  #  git:
  #    url: https://github.com/simolus3/drift.git
  #    ref: develop
  #    path: drift
  #drift: 1.7.1
  sqlite3_flutter_libs: ^0.5.7


  #---Url launcher
  url_launcher: ^6.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  #---badges for icons
  badges: ^2.0.3

  #---flutter webview plugin displace
  #flutter_webview_plugin:
  #    git: https://github.com/nuc134r/flutter_webview_plugin.git

  #---logging:
  logging: ^1.0.2
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.1
  package_info_plus: ^3.0.0
  firebase_performance: ^0.9.0+1

  #---db_inspector
  drift_db_viewer: ^2.0.0

  #---validators
  email_validator: ^2.1.17

  #---list extensions
  collection: ^1.16.0

  #---flag
  flag: ^6.0.0

  #---flutter_native_splash
  #flutter_native_splash: ^2.2.16


  #---Animated splashscreen:
  #animated_splash_screen: ^1.3.0
#---Icons---



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_round.png"
  adaptive_icon_background: "#666666"

dev_dependencies:
  flutter_test:
    sdk: flutter

  #---swagger changes---
  build_runner: ^2.1.11
  chopper_generator: ^6.0.0
  json_serializable: ^6.2.0
  swagger_dart_code_generator: ^2.8.7

  #---Launcher icons---
  flutter_launcher_icons: ^0.11.0

  #---floor generators---
  #floor_generator: ^1.2.0

  #---drift generators---
  drift_dev: ^2.3.0
  #drift_dev: 1.7.1

  #--- analyzer
  #analyzer: ^4.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

`build.yaml`:
```
targets:
  $default:
    sources:
      - swaggers/**
      - lib/**
      - lib/native/drift/native/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          output_folder: "lib/services/api/generated"
```

Please give a note if you neeed db files to investigate.

**Comment by simolus3** [comment]
I couldn't reproduce the issue in this repository after upgrading to the latest analyzer packages. That said,

```
[WARNING] drift_dev on lib/services/drift/database/m_work_database.dart:
Could not resolve Dart library package:mwork/services/drift/database/m_work_database.dart
This builder requires Dart inputs without syntax errors.
However, package:mwork/services/drift/database/m_work_database.dart (or an existing part) contains the following errors.
m_work_database.dart:37:1: Expected a method, getter, setter or operator declaration.
m_work_database.dart:38:3: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
m_work_database.dart:38:3: Expected to find ';'.
And 11 more...
```

Are these syntax errors legit? If they are, can you fix them in `m_work_database.dart`? If not, having the source file would help investigate :+1:

**Comment by RoarGronmo** [comment]
The clue is that the `m_work_database.g.dart` file isn't created at all with the newest ones, so all references to `m_work_database.g.dart` are broken...

All works fine with 
```
dependencies:
  _fe_analyzer_shared: 51.0.0
  analyzer: 5.3.1
```

Broken with:
```
dependencies:
  _fe_analyzer_shared: 52.0.0
  analyzer: 5.4.0
```

What files do you need ?

**Comment by simolus3** [comment]
The build log says that there are syntax errors in `m_work_database.dart`, which I assume is a regular source file (it's not a `.g.dart` file).

> What files do you need ?

Having that source file would be good to check the syntax error.

**Comment by RoarGronmo** [comment]
The `m_work_database.dart` is ok, but it references `m_work_database.g.dart` which disappears when using the new analyzer files.
(note "renamed" with .txt)
[m_work_database.dart.txt](https://github.com/simolus3/drift/files/10383036/m_work_database.dart.txt)

There are approx 30 table files, do you need them too ?

**Comment by RoarGronmo** [comment]
Note, there are other files generated which is not directly related to drift, and those are generated ok. So there shouldn't be any influences from that library AFAIK.

```
  #---swagger changes---
  build_runner: ^2.1.11
  chopper_generator: ^6.0.0
  json_serializable: ^6.2.0
  swagger_dart_code_generator: ^2.8.7
```

**Comment by RoarGronmo** [comment]
I'll try to make a proof-of-concept project, just to pinpoint where the trouble is. But first I'll check some other (older) projects which uses drift first. It may take a while.

**Comment by RoarGronmo** [comment]
An older project, with similar (but not quite the same) setup works fine with newest analyzer files:

This `pubspec.yaml` is like this:

```
name: m_work_admin
description: mWork admin module.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+9

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  #---Google Maps---
  google_maps_flutter: ^2.1.12
  google_maps_flutter_web: ^0.4.0+2
  google_maps_cluster_manager: ^3.0.0+1
  flutter_google_street_view: ^3.0.0
  pointer_interceptor: ^0.9.3+2
  maps_toolkit: ^2.0.1


  #---Charts
  charts_flutter: ^0.12.0

  #---Dropdown menu 2
  dropdown_button2: ^1.7.2

  # ---logging
  logging: ^1.0.2

  # ---visibility detector
  visibility_detector: ^0.3.3

  # ---flutter settings screen //May be obsolete, no updates since april 2021 and upcoming errors
  #flutter_settings_screens: ^0.3.2-null-safety

  # ---new preference attempt
  pref: ^2.6.0

  # ---Microsoft Client Access Web
  msal_js: ^2.14.0

  #---Aad Oauth
  aad_oauth: ^0.4.0

  # ---Bidirectional listview
  bidirectional_listview: ^1.0.3
  infinite_listview: ^1.1.0

  #---ScrollableListView
  scrollable_positioned_list: ^0.3.2

  # ---Swagger changes
  chopper: ^6.0.0
  json_annotation: ^4.6.0

  #---linked_scroll_controller
  linked_scroll_controller: ^0.2.0

  # ---Drift
  #drift: ^1.7.1
  drift: ^2.0.2+1
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11
  path: ^1.8.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  #--Formatter
  intl: ^0.17.0

  #--package info
  package_info_plus: ^3.0.2
  firebase_core: ^2.3.0
  firebase_performance: ^0.9.0+6
  google_fonts: ^3.0.1

  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ---Swagger changes
  build_runner: ^2.2.0
  chopper_generator: ^6.0.0
  json_serializable: ^6.3.1
  swagger_dart_code_generator: ^2.7.4

  # ---Drift
  #drift_dev: ^1.7.0
  drift_dev: ^2.0.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
  #  - family: RobotoMono
  #    fonts:
  #      - asset: fonts/RobotoMono-Regular.ttf
  #      - asset: fonts/RobotoMono-Bold.ttf
  #        weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

So the problem lies within the difference between those two projects somewhere...
