### ISSUE TITLE
Modular generate do not import source tables file

### ISSUE THREAD

**Issue by NikitaVasin** [simolus3/moor#2263]
```
//--- DataBase file ------

import 'database.drift.dart';

@DriftDatabase(
  tables: [
    Companies,
  ],
)
class Database extends $Database {
  Database(super.e);

  @override
  int get schemaVersion => 1;
}

//----- Other module file -----

@DataClassName('Company')
class Companies extends Table with BaseDriftTable {
  TextColumn get name => text().named('name')();
}

mixin BaseDriftTable on Table {
  TextColumn get id => text().clientDefault(() => const Uuid().v1())();
}

//-----Generated module file ------

// ignore_for_file: type=lint
import 'package:drift/drift.dart' as i0;
import 'package:drift_test/common/data/second_module.drift.dart' as i1;
import 'package:uuid/uuid.dart' as i2;

//! missing source file import
//! import 'package:drift_test/common/data/second_module.dart';

class $CompaniesTable extends Companies
    with i0.TableInfo<$CompaniesTable, i1.Company> { /* ... */ }

```

**Comment by NikitaVasin** [comment]
build.yaml file
```
targets:
  $default:
    builders:
      drift_dev:
        enabled: false
      drift_dev:analyzer:
        enabled: true
      drift_dev:modular:
        enabled: true
```
