### ISSUE TITLE
libsqlite3.so not found

### ISSUE THREAD

**Issue by Langellotti** [simolus3/moor#2314]
Hello, since I updated Flutter to version 3.7.3, I encounter this compilation bug :

```
E/flutter ( 5204): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '/data/data/com.example.floatnotes/lib/libsqlite3.so': dlopen failed: library "/data/data/com.example.floatnotes/lib/libsqlite3.so" not found
E/flutter ( 5204): #0      DriftCommunication.request (package:drift/src/remote/communication.dart:116:66)
E/flutter ( 5204): #1      _RemoteQueryExecutor.ensureOpen (package:drift/src/remote/client_impl.dart:158:10)
E/flutter ( 5204): #2      LazyDatabase.ensureOpen.<anonymous closure> (package:drift/src/utils/lazy_database.dart:61:49)
```

My device is Android v13.
My OS is Debian (last version)

I did modify the settings.gradle as advised, but without success.
Flutter doctor is ok, and all my dependencies are up to date.

Does anyone have a solution? THANKS !

**Comment by Langellotti** [comment]
My pubspec.yaml : 

```yaml
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bloc: ^8.1.1
  args: ^2.4.0
  build_runner: ^2.3.3
  collection: ^1.17.0
  firebase_core: ^2.5.0
  firebase_core_platform_interface: ^4.5.3
  firebase_core_web: ^2.1.1
  fixnum: ^1.1.0
  google_sign_in_android: ^6.1.6
  google_sign_in: ^5.4.4
  googleapis: ^10.1.0
  js: ^0.6.5
  matcher: ^0.12.13
  meta: ^1.8.0
  source_gen: ^1.2.7
  test_api: ^0.4.16
  win32: ^3.1.3
  xdg_directories: ^1.0.0
  cupertino_icons: ^1.0.2
  drift: ^2.5.0
  drift_dev: ^2.5.2
  drift_sqflite: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  path: ^1.8.2
  path_provider: ^2.0.0
  path_provider_linux : ^2.1.8
  provider: ^6.0.4
  screenshot: ^1.2.3
  scrollable_positioned_list: ^0.3.5
  sqflite: ^2.2.0+3
  #sqflite_common_ffi: ^2.2.1+1
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
```
