### ISSUE TITLE
Problem with the generated classes. 'Table' is already defined

### ISSUE THREAD

**Issue by enrique-lozano** [simolus3/moor#2422]
When I generated the code for a simple table, in the resulting .g.dart file I get the following error: 

```
The name 'Table' is defined in the libraries 'package:drift/src/dsl/dsl.dart (via package:drift/drift.dart)' and 'package:flutter/src/widgets/table.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```

I'm using a simple .drift file here: 

```
CREATE TABLE IF NOT EXISTS currencies (
    code TEXT NOT NULL PRIMARY KEY,
    symbol TEXT NOT NULL
) AS Currency;
```

My <code>pubspec.yaml</code> file:

```

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Drift
  drift: ^2.5.0
  path_provider: ^2.0.13
  http: ^0.13.5
  sqlite3: ^1.9.3
  sqlite3_flutter_libs: ^0.5.13

  # Riverpod
  provider: ^6.0.3
  flutter_riverpod: ^2.3.1
  riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  collection: ^1.17.0
  equatable: ^2.0.5
  intl: ^0.17.0
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  path: ^1.8.2
  go_router: ^6.2.0
  async: ^2.10.0
  flutter_svg: ^2.0.5
  permission_handler: ^10.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.2.0
  riverpod_generator: ^2.1.3
  drift_dev: ^2.4.0
```

Seems that the name Table is already in use by flutter internally.
