### ISSUE TITLE
Add coverage ignore to generated files

### ISSUE THREAD

**Issue by Dall127** [simolus3/moor#2541]
**Describe the solution you'd like**

During the generation of the auto-generated database code, it would be appreciated if it didn't get counted in code coverage

Below I've added the line that would need to be added for that to happen 
```
// coverage:ignore-file
```

**Comment by Dall127** [comment]
Update, after doing research I found that one can do this without the respective code generator implementing it. Simply update (or create) the build.yaml file and add the following lines

```
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          preamble: |
            // coverage:ignore-file
```

https://github.com/dart-lang/source_gen/pull/636#issuecomment-1399294260
