### ISSUE TITLE
Changing the pattern of generated files

### ISSUE THREAD

**Issue by AlexBolot** [simolus3/moor#2552]
Currently, generated files are named `<my_file>.g.dart`, which in my previous experience can cause issues within the IDE or other related tools, who can have trouble handling the file as a Dart file.

It would be awesome to add a config file inside the project to be able to change this matching. For example I could specify the following pattern `<my_file>_drift.dart`

**Comment by simolus3** [comment]
> Currently, generated files are named `<my_file>.g.dart`, which in my previous experience can cause issues within the IDE or other related tools, who can have trouble handling the file as a Dart file.

Note that the file extension is still `.dart`, so I doubt that any tool will have issues reading that file. None of the Dart IDEs and tools I've used so far had a problem with that.

That said, you [can change the patterns of generated files](https://simonbinder.eu/posts/build_directory_moves/) by creating a file called `build.yaml` with this content:

```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '.dart': '_generated.dart'
```
