### ISSUE TITLE
Build_Runner errors out for multi dialects

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2592]
So i am trying to add multiple dialects i.e postgres and sqlite. Following the docs my build.yaml looks as follows

```
targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect:
              - sqlite
              - postgres
            options:
              version: "3.34"
```

I get the following error when running the build_runner:

```
PS D:\Github\psql> dart run build_runner build -d
[INFO] Generating build script completed, took 443ms
[SEVERE]
CheckedFromJsonException
Could not create `DialectOptions`.
There is a problem with "dialect".
`[sqlite, postgres]` is not one of the supported values: sqlite, mysql, postgres, mariadb
```
