### ISSUE TITLE
Migrating from unix timestamp to text

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#2624]
**Using last develop version, I am trying to migrate as [described in the documentation](https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#migrating-between-the-two-modes), but I get this error:**

```
E/flutter (11193): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid date format
E/flutter (11193): **1695215813Z**
E/flutter (11193): #0      DateTime.parse (dart:core/date_time.dart:358:7)
E/flutter (11193): #1      SqlTypes.read (package:drift/src/runtime/types/mapping.dart:179:31)
E/flutter (11193): #2      $ProfilesTable.map (package:myapp/db/db_settings.g.dart:662:12)
```

`  DateTimeColumn get created_date => dateTime().nullable().withDefault(currentDateAndTime)();`

db_settings.g.dart:
```
      created_date: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${effectivePrefix}created_date']),
```

I am using this function:
```
  Future<void> migrateFromUnixTimestampsToText(Migrator m) async {
    for (final table in allTables) {
      final dateTimeColumns = table.$columns.where((c) => c.type == DriftSqlType.dateTime);

      if (dateTimeColumns.isNotEmpty) {
        // This table has dateTime columns which need to be migrated.
        await m.alterTable(TableMigration(
          table,
          columnTransformer: {
            for (final column in dateTimeColumns)
            // We assume that the column in the database is an int (unix
            // timestamp), use `fromUnixEpoch` to convert it to a date time.
            // Note that the resulting value in the database is in UTC.
              column: DateTimeExpressions.fromUnixEpoch(column.dartCast<int>()),
          },
        ));
      }
    }
  }
```
In the new Migration
```
       if (from < 68) {
         migrateFromUnixTimestampsToText(m);
       }
```

build.yaml:
```
targets:
  $default:
    builders:
      drift_dev:
        options:
          write_from_json_string_constructor: true
          mutable_classes: true
          generate_values_in_copy_with: false
          store_date_time_values_as_text: true
```
