### ISSUE TITLE
tables.moor could not be imported

### ISSUE THREAD

**Issue by MahmoodAliL** [simolus3/moor#2706]
**Describe the bug**

The tables.moor file and other files which contain SQL Statment can't imported, I expected it to work like before and all files should be generated, I tried to change the SQL file extension to .drift but another issue with build_runner happened `drift_dev:preparing_builder may output lib/data_source/tables.expr.temp.dart. Potential outputs must be unique across all builders.`

```
drift_dev on lib/data_source/app_database.dart:
line 23, column 7 of package:debt_record/data_source/app_database.dart: `tables.moor` could not be imported
 
[WARNING] drift_dev on lib/data_source/app_database.dart:
line 23, column 7 of package:debt_record/data_source/app_database.dart: `tables.moor` could not be imported
   ╷
23 │ class AppDatabase extends _$AppDatabase {
   │       ^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data_source/app_database.dart:
line 23, column 7 of package:debt_record/data_source/app_database.dart: `../features/home/data/sql.moor` could not be imported
   ╷
23 │ class AppDatabase extends _$AppDatabase {
   │       ^^^^^^^^^^^
   ╵
.
.
```

**pubspec.yaml** 
```

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.17
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  drift_dev: ^2.13.0
```

**Comment by simolus3** [comment]
Do you have a `build.yaml` configuration with multiple targets? Otherwise, I think the "both drift\_dev and drift\_dev may output" error could occur if you have both a `.moor` and a `.drift` file with the same name except for the extension. Renaming the file should work, but so should `.moor` files. I'll take a look and will try to reproduce this.

**Comment by MahmoodAliL** [comment]
### build.yaml 


```
targets:
  $default:
    builders:
      drift_dev:
        options:
          apply_converters_on_variables: true
```

Yes, I have file with same name and extension all of theme was `sql.moor`

### AppDatabase

```
@DriftDatabase(
  include: {
    'tables.moor',
    '../features/home/data/sql.moor',
    '../features/person/data/detail/sql.moor',
    '../features/person/data/add/sql.moor',
    '../features/debt_payback/data/sql.moor',
    '../shared/data/sql.moor',
  },
)
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.db);
.
.
.      
```

I will try to make the name of files different from each other
