### ISSUE TITLE
Table reference `` not found, is it added to this view as a getter?

### ISSUE THREAD

**Issue by Heinrich-vanNieuwenhuizen** [simolus3/moor#2715]
**Describe the bug**
We are trying to upgrade our drift from 1.7.1 to the latest version 2.13.1, but we are getting build errors on our views.
Creating a table in drift and from the drift table create a dart view results in Table reference `comboGroup` not found, is it added to this view as a getter?

See below unit test
```
 test('generates views from drift tables', () async {
    final debugLogger = Logger('driftBuild');
    debugLogger.onRecord.listen((e) => print(e.message));
    final result = await emulateDriftBuild(
      inputs: {
        'a|lib/drift/datastore/views/combo_group_view.dart': '''
import 'package:drift/drift.dart';
import '../datastore_db.dart';
abstract class ComboGroupView extends View {
  late final DatastoreDb attachedDatabase;
  IntColumn get comboGroupID => attachedDatabase.comboGroup.comboGroupID;
  IntColumn get objectNumber => attachedDatabase.comboGroup.objectNumber;
  TextColumn get stringText => attachedDatabase.stringTable.stringText;
  // Table get comboGroup;
  // ComboGroup get comboGroup;
  // ComboGroup get comboGroup => attachedDatabase.comboGroup;
  late final ComboGroup comboGroup;
  @override
  Query as() => select([
        comboGroupID,
        objectNumber,
        stringText,
      ]).from(comboGroup).join([
        innerJoin(
            attachedDatabase.stringTable,
            attachedDatabase.stringTable.stringNumberID
                .equalsExp(attachedDatabase.comboGroup.nameID)),
      ]);
}
''',
        'a|lib/drift/datastore/tables/combo_group.drift': '''
CREATE TABLE [COMBO_GROUP](
	[ComboGroupID] [int] NOT NULL PRIMARY KEY,
	[HierStrucID] [bigint] NULL,
	[ObjectNumber] [int] NULL,
	[NameID] [bigint] NULL,
	[OptionBits] [nvarchar](8) NULL,
	[SluIndex] [int] NULL,
	[HhtSluIndex] [int] NULL);
''',
        'a|lib/drift/datastore/tables/string_table.drift': '''
CREATE TABLE [STRING_TABLE](
	[StringID] [bigint] NOT NULL PRIMARY KEY,
	[StringNumberID] [bigint] NULL,
	[LangID] [int] NULL,
	[IsVisible] [bit] NOT NULL DEFAULT ((1)),
	[IsDeleted] [bit] NOT NULL DEFAULT ((0)),
	[HierStrucID] [bigint] NULL,
	[PosRef] [bigint] NULL,
	[StringText] [nvarchar](128) NULL
);
       ''',
        'a|lib/drift/datastore/datastore_db.dart': '''
        import 'package:drift/drift.dart';
        import 'views/combo_group_view.dart';
        
        part 'datastore_db.g.dart';
        @DriftDatabase(
          views: [ComboGroupView],
          include: {'tables/combo_group.drift'},
        )
        class DatastoreDb extends _\$DatastoreDb {
        }
        '''
      },
      modularBuild: true,
      options: BuilderOptions({'assume_correct_reference': true}),
      logger: debugLogger
    );
}
```

**Comment by simolus3** [comment]
I'm a bit surprised that this has ever worked :thinking: There's no reliable way to reference specific elements defined in a `.drift` file in a `.dart` file at the moment.

**Comment by Heinrich-vanNieuwenhuizen** [comment]
In version 1.7.1
if you
```
abstract class ComboGroupView extends View {
  late final DatastoreDb attachedDatabase;
  // IntColumn get objectNumber => attachedDatabase.majorGroup.objectNumber;

  IntColumn get comboGroupID => attachedDatabase.comboGroup.comboGroupID;
  IntColumn get objectNumber => attachedDatabase.comboGroup.objectNumber;
  TextColumn get stringText => attachedDatabase.stringTable.stringText;
  //
  // IntColumn get menuItemMasterObjNum =>
  //     attachedDatabase.combo.menuItemMasterObjNum;
  // IntColumn get mainItemComboGroupObjNum =>
  //     attachedDatabase.combo.mainItemComboGroupObjNum;

  @override
  Query as() => select([
        comboGroupID,
        objectNumber,
        stringText,
      ]).from(attachedDatabase.comboGroup).join([
        innerJoin(
            attachedDatabase.stringTable,
            attachedDatabase.stringTable.stringNumberID
                .equalsExp(attachedDatabase.comboGroup.nameID)),
      ]);
}
```
it would keep the attachedDatabase.comboGroup

**Comment by greenking19** [comment]
I'm having this problem right now.
Is this problem solved now?

**Comment by Heinrich-vanNieuwenhuizen** [comment]
Hi @greenking19,

Yes, it is. 

You have to add the assume_correct_refence to your build.yaml. I've included the example I use below.
``` yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: false
          skip_verification_code: true
# generate_values_in_copy_with (defaults to true): Generates a Value<T?> instead of T?
# for nullable columns in copyWith. This allows to set columns back to null (by using Value(null)).
# Passing null was ignored before, making it impossible to set columns to null.
          generate_values_in_copy_with : false
          mutable_classes : false
          named_parameters_always_required : false
          apply_converters_on_variables : false
          scoped_dart_components : false
          assume_correct_reference : true
```
it should be available in the latest version of drift.
