### ISSUE TITLE
Table generation with type extention generates "const" constructor

### ISSUE THREAD

**Issue by tobzilla90** [simolus3/moor#2735]
**Bug report**
Table generation with type extension generates "const" constructor which leads to 
**Error: A constant constructor can't call a non-constant super constructor.**

Example to reproduce: 
```
abstract class HasId extends DataClass {
  abstract final int id;
}

@DataClassName('Demo', extending: HasId)
class Demos extends Table with AutoIncrementingPrimaryKey {
  TextColumn get name => text()();
}

mixin AutoIncrementingPrimaryKey on Table {
  IntColumn get id => integer().autoIncrement()();
}
```

above code will generate a constructor for `Demo` in `database.g.dart` like this:
```
...
const Demo({required this.id, required this.name});
...
```

but it should be generated without the "const" keyword. 

**package version**
```
dependencies:
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  drift: ^2.13.0
dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.0
```

**Workaround**
You can manually delete the const in front of the constructor in the generated `database.g.dart` file. But you have to do this every time you generate the file. 

**reference to docs**
https://drift.simonbinder.eu/api/drift/dataclassname/extending
