### ISSUE TITLE
Add coverage ignore for generated files

### ISSUE THREAD

**Issue by Ragueel** [simolus3/moor#2824]
**Is your feature request related to a problem? Please describe.**
I am running `flutter test --coverage` and generated files from drift are included in coverage hits and misses. 

**Describe the solution you'd like**
When build_runner generates files they should have the following comment at the top of the files.
```
// coverage:ignore-file
```

The feature does not seem so hard, I can try to create a pull-request with it, but just not sure where exactly should I add it.

**Comment by simolus3** [comment]
In its default setup, drift uses `source_gen` to contribute generated code to the build system. That builder already has a `preamble` option which might work here. You can create a `build.yaml` file at the top of your project (next to its pubspec) with this content:

```yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          preamble: |
             // coverage:ignore-file
```

If that doesn't work, we can implement it in drift by adding a similar option to [DriftOptions](https://github.com/simolus3/drift/blob/develop/drift_dev/lib/src/analysis/options.dart) and then writing that next to this: https://github.com/simolus3/drift/blob/09c6cf0b4e968204be5eda63614e815078fea970/drift_dev/lib/src/backends/build/drift_builder.dart#L424
