### ISSUE TITLE
Incorrect Variable Bindings in Postgres Transactions

### ISSUE THREAD

**Issue by loopnyapy** [simolus3/moor#2894]
**What we are trying to do**
We are trying to run queries within a transaction that includes `db.insertReturning`.

**Expected**
I expect that, similar to any other query not within a transaction, `?` should be replaced with `@`, and the appropriate method, such as `PgDelegate.runInsert`, should be called for `db.insertReturning`.

**Actual**
Instead, `PgDelegate.runSelect` is called with an unprepared `statement` argument, resulting in the use of variable binding `?` instead of `@`.

Simple code example:
```dart
  Future<Tag> createTag(Tag tag) =>
      database.transaction(() {
        return database
            .into(database.tags)
            .insertReturning(tag.toCompanion());
      });
```

Pubspec.yaml:
```yaml
dependencies:
  drift_postgres: ^1.1.0
  drift: ^2.15.0

dev_dependencies:
  drift_dev: ^2.15.0
```

I look forward to any insights or solutions regarding this issue. Thank you 🙏
