### ISSUE TITLE
File table and dart:io File clash

### ISSUE THREAD

**Issue by albe-jj** [simolus3/moor#2904]
If I have `import 'dart:io' as io;`  in the file where I define the database tables, and a table named `@DataClassName("File")`  then in the database.g.dart file it uses io.File instead of the File dataclass. 

Removing the  `import 'dart:io' as io;`  from database.dart resolve the issue.

**Comment by simolus3** [comment]
Thanks for the report! Unfortunately it's a bit tricky to know which import was meant because that part of the code is not set up to deal with exports correctly, but at least for `dart:` vs `package:` URIs we should be able to prevent this.

**Comment by bbjay** [comment]
I also ran into this issue after upgrading from 2.12.1 to 2.16.0
Is there a way to test the fix or is a 2.17.0 release imminent anyway?

**Comment by simolus3** [comment]
You can use the current development version of the builder until the next release (no ETA yet, sorry):

```yaml
dependency_overrides:
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
```

Let me know if that fixes the issue for you.
