### ISSUE TITLE
Package import mismatch in generated file

### ISSUE THREAD

**Issue by petrnymsa** [simolus3/moor#2985]
**Describe the bug**

When using `version` package ([https://pub.dev/packages/version](https://pub.dev/packages/version)) and `sqlite3` at the same time, there is clash with imports even when of the package is aliased.

```yaml
dependencies:
  drift: ^2.17.0
  version: ^3.0.2
  sqlcipher_flutter_libs: ^0.5.4
  sqlite3: ^2.0.0
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.17.0
```

db.dart
```dart
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart' as path_provider;
import 'package:sqlite3/sqlite3.dart' as sqlite;
import 'package:version/version.dart';

part 'db.drift.dart';
part 'user_table.dart';

@DriftDatabase(tables: [UserProfiles])
class LocalDatabase extends _$LocalDatabase {
  @override
  int get schemaVersion => 1;

  LocalDatabase({QueryExecutor? executor}) : super(executor ?? _openConnection());

  static bool _debugCheckHasCipher(sqlite.Database database) {
    return database.select('PRAGMA cipher_version;').isNotEmpty;
  }

  static LazyDatabase _openConnection() {
    return LazyDatabase(() async {
      final dbFolder = await path_provider.getApplicationDocumentsDirectory();
      final file = File(p.join(dbFolder.path, 'db.sqlite'));

      return NativeDatabase(
        file,
        setup: (rawDb) {
          assert(_debugCheckHasCipher(rawDb), 'check cipher');
          rawDb.execute("PRAGMA key = 'XXX';");
        },
        logStatements: true,
      );
    });
  }
}

```

UserTable
```dart
part of 'db.dart';

@DataClassName('UserProfileRow')
class UserProfiles extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get userName => text()();
  TextColumn get apiVersion => text().map(const _VersionConverter())();

  @override
  List<Set<Column<Object>>> get uniqueKeys => [
        {userName},
      ];

  const UserProfiles();
}

// Version is from `Version` package
class _VersionConverter extends TypeConverter<Version, String> {
  const _VersionConverter();

  @override
  Version fromSql(String fromDb) {
    return Version.parse(fromDb);
  }

  @override
  String toSql(Version value) {
    return value.toString();
  }
}
```

sqlite3 package is aliased.

Generated part

db.drift.dart
```dart

// in 	$UserProfilesTable  

// error: A value of type '_VersionConverter' can't be assigned to a variable of type 'TypeConverter<Version, String>'.
// Try changing the type of the variable, or casting the right-hand type to 'TypeConverter<Version, String>
  static TypeConverter<sqlite.Version, String> $converterapiVersion =
      const _VersionConverter();

```

Error: 

```
A value of type '_VersionConverter' can't be assigned to a variable of type 'TypeConverter<Version, String>'.
Try changing the type of the variable, or casting the right-hand type to 'TypeConverter<Version, String>
```

**notice that Version is prefixed with sqlite.**

build.yaml configuration
```yaml
targets:
  $default:
    auto_apply_builders: true
    builders:
      drift_dev:not_shared:
        enabled: true
      drift_dev:preparing_builder:
        enabled: true
      drift_dev:drift_dev:
        enabled: false

```

Dart version

```
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "windows_x64"
```

## Expected behavior

Drift will not mismatch imported aliases Version (from package Version) and sqlite3.Version
