### ISSUE TITLE
Error running MoorGenerator NoSuchMethodError: The getter 'typeConverter' was called on null.

### ISSUE THREAD

**Issue by jokerr287** [simolus3/moor#300]
I am getting this error even though it just a simple database file. I am new to flutter but i suspect this error is because of dependencies. Please help urgently.

database.dart
```
import 'package:moor/moor.dart';

part 'database.g.dart';

class Items extends Table {
  IntColumn get id => integer().autoIncrement().call();
  TextColumn get item => text().withLength(min: 1, max:50).call();
  IntColumn get parent =>integer().call();
  BoolColumn get comleted => boolean().withDefault(Constant(false)).call();

}

@UseMoor(tables: [Items])
class AppDatabase {
  
  
}
```

dependency 
```
dependencies:
  flutter:
    sdk: flutter
  moor: # use the latest version
  moor_ffi: # use the latest version
  path_provider:
  path:

dev_dependencies:
  build_runner:
  moor_generator: 
  flutter_test:
    sdk: flutter
```

Error is generated after I run flutter packages pub run build_runner build  command.
Error running MoorGenerator
NoSuchMethodError: The getter 'typeConverter' was called on null.
Receiver: null
Tried calling: typeConverter
[SEVERE] moor_generator:moor_generator on lib/database.dart (cached):
Error running DaoGenerator
NoSuchMethodError: The getter 'typeConverter' was called on null.
Receiver: null
Tried calling: typeConverter
