### ISSUE TITLE
Unable to override `runs_before` in `build.yaml` due to `Unrecognized keys` exception

### ISSUE THREAD

**Issue by exaby73** [simolus3/moor#3068]
**Describe the bug**

I am trying to override the `runs_before` in `build.yaml` to try to debug an issue with another package running it's generation before drift. But drift is not allowing me to override it. Here is my `build.yaml`:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          runs_before:
            - superclass
          sql:
            dialects:
              - postgres
```

And here is the error:

```console
Unrecognized keys: [runs_before]; supported keys: [write_from_json_string_constructor, override_hash_and_equals_in_result_sets, skip_verification_code, use_data_class_name_for_companions, use_column_name_as_json_key_when_defined_in_moor_file, use_sql_column_name_as_json_key, generate_connect_constructor, generate_manager, sqlite_modules, sqlite, sql, data_class_to_companions, mutable_classes, raw_result_set_data, apply_converters_on_variables, generate_values_in_copy_with, named_parameters, named_parameters_always_required, scoped_dart_components, store_date_time_values_as_text, case_from_dart_to_sql, write_to_columns_mixins, assume_correct_reference, has_separate_analyzer, preamble, fatal_warnings]
```

I believe this error is thrown by `json_serializable`. I think it originates [here](https://github.com/simolus3/drift/blob/482b7c777159c9db0b88ef91ebbd538993cdc5db/drift_dev/drift_dev.build.yaml#L34)
