### ISSUE TITLE
Why is the generated file not with the “.drift.dart” suffix but with the “.g.dart” suffix? How can I make it generate with the “.drift.dart” suffix?

### ISSUE THREAD

**Issue by ddxl123** [simolus3/moor#3158]
Why is the generated file not with the “.drift.dart” suffix but with the “.g.dart” suffix? How can I make it generate with the “.drift.dart” suffix?

To generate a `.drift.dart` file in the Flutter A folder (which requires the drift_dev builder), and a `.g.dart` file in the Flutter B folder (which can be generated without writing a `build.yaml` configuration), folder B depends on folder A. This means that folder A must be generated before folder B can be generated. 
Here is my `build.yaml` file that achieves this effect, but there is an issue: if the file extension generated in folder A is ".g.dart", an error occurs: 
```
[SEVERE] json_serializable on lib/drift_and_http/httper/httper.dart (cached):

Could not generate `fromJson` code for `fragment_group`.
To support the type `InvalidType` you can:
* Use `JsonConverter`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
* Use `JsonKey` fields `fromJson` and `toJson`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
package:aaa_memory/drift_and_http/httper/dto_vo_bo/bo/bo.dart:35:17
   ╷
35 │   FragmentGroup fragment_group;
   │                 ^^^^^^^^^^^^^^
   ╵
[SEVERE] Failed after 143ms
```
However, if I manually change the file extension generated in folder A to `.drift.dart`, there is no problem.

build.yaml
```
targets:
  $default:
    builders:
      drift_dev|drift_builder:
        enabled: true
        options:
          mutable_classes: true
          named_parameters: true
          named_parameters_always_required: true
        generate_for:
          - lib/drift_and_http/drift/DriftDb.dart
      json_serializable|json_serializable_builder:
        enabled: true
        options:
          generate_for:
          - lib/drift_and_http/httper/httper.dart
```

`FragmentGroup` is `DataClass`

BO class：
```
@JsonSerializable()
class FragmentGroupWithJumpWrapper {

  ///
  FragmentGroup fragment_group;

  ///
  FragmentGroup? jump_fragment_group;

  FragmentGroupWithJumpWrapper({
    required this.fragment_group,
    required this.jump_fragment_group,
  });

  factory FragmentGroupWithJumpWrapper.fromJson(Map<String, dynamic> json) => _$FragmentGroupWithJumpWrapperFromJson(json);

  Map<String, dynamic> toJson() => _$FragmentGroupWithJumpWrapperToJson(this);
}
```
