### ISSUE TITLE
[drift_dev]: `schema_steps` does not work for Postgres databases

### ISSUE THREAD

**Issue by exaby73** [simolus3/moor#3261]
I have the following table `users` defined like:

```dart
class Users extends Table with CreatedAt {
  UuidColumn get id => customType(PgTypes.uuid).withDefault(genRandomUuid())();

  TextColumn get name => text()();

  TextColumn get email => text().unique()();

  TextColumn get password => text()();

  @override
  Set<Column> get primaryKey => {id};
}
```

Notice I am using `getRandomUuid()` as the default. The `CreatedAt` mixin has the following:

```dart
mixin CreatedAt on Table {
  TimestampColumn get createdAt =>
      customType(PgTypes.timestampWithTimezone).withDefault(now())();
}
```

With this column, I am using `now()` as the default.

Running `dart run drift_dev schema steps` after doing a dump generates the versions file, without the import for `drift_postgres`. Adding the import manually (which is a workaround I am willing to automate), the values of `now()` and `getRandomUuid()` do not adhere to the `DriftAny` type in the generated code. Here is a snippet of the generated code for a `users` table from the previous schema version which fails:

```dart
i1.GeneratedColumn<i1.DriftAny> _column_0(String aliasedName) =>
    i1.GeneratedColumn<i1.DriftAny>('created_at', aliasedName, false,
        type: i1.DriftSqlType.any, defaultValue: now()); // <- Error here
i1.GeneratedColumn<i1.DriftAny> _column_1(String aliasedName) =>
    i1.GeneratedColumn<i1.DriftAny>('id', aliasedName, false,
        type: i1.DriftSqlType.any, defaultValue: genRandomUuid()); // <- Error here
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('password', aliasedName, false,
        type: i1.DriftSqlType.string);
```

Let me know if there's any more information I can provide

### Environment information:

```console
drift: 2.20.3
drift_dev: 2.20.3
drift_postgres: 1.3.0
postgres: 3.4.0
```

### `build.yaml`

```yaml
targets:
  drift:
    auto_apply_builders: false
    builders:
      drift_dev:analyzer:
        enabled: true
        options: &options
          store_date_time_values_as_text: true
          named_parameters: true
          sql:
            dialect: postgres
      drift_dev:modular:
        enabled: true
        options: *options

  $default:
    dependencies:
      - ":drift"
    builders:
      drift_dev:
        enabled: false
```
