### ISSUE TITLE
Unsupported operation: Exporting Dart-defined views into a schema is not currently supported

### ISSUE THREAD

**Issue by wrouesnel** [simolus3/moor#3285]
**Description**

When exporting the Drift schema to JSON with the command:

```
dart run drift_dev schema dump lib/services/database/database.dart drift_schemas/
```

and a view attached to the database object - e.g.

```
@DriftDatabase(tables: [
  PartItems,
  CapabilityItems,
], views: [
  CapabilityCurrentPartItems
])
class AppDatabase extends _$AppDatabase {
// etc. ...
}
```

The following error is generated:

```
Unhandled exception:
Unsupported operation: Exporting Dart-defined views into a schema is not currently supported
#0      SchemaWriter._entityToJson (package:drift_dev/src/services/schema/schema_files.dart:90:9)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#3      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:882:20)
#4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#6      new List.of (dart:core-patch/array_patch.dart:39:18)
#7      Iterable.toList (dart:core/iterable.dart:498:7)
#8      SchemaWriter.createSchemaJson (package:drift_dev/src/services/schema/schema_files.dart:46:64)
#9      DumpSchemaCommand.run (package:drift_dev/src/cli/commands/schema/dump.dart:78:49)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     DriftDevCli.run (package:drift_dev/src/cli/cli.dart:69:5)
<asynchronous suspension>
#12     run (package:drift_dev/src/cli/cli.dart:20:12)
<asynchronous suspension>
Could not dump schema
```

Since the generation of migration code with drift_dev depends on the the schema dump process AFAIK, using views in anyway would seem to break the process?

**Versions**

```
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: drift
  drift_flutter:
    git:
      url: https://github.com/simolus3/drift.git
      path: drift_flutter
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      path: drift_dev
```

Current commit is d7cc547836cdce038f76395908e137afd96cbc96
