### ISSUE TITLE
Error(s) implementing guided migrations

### ISSUE THREAD

**Issue by frankvollebregt** [simolus3/moor#3345]
**Describe the bug**
Until recently, I used separate `drift_dev` scripts to generate the schema and steps. When I just looked up the command (as I used to do each time) I noticed that there's now an all-in-one script that takes care of this. Awesome!

Unfortunately, it doesn't quite work for me when I try to follow the steps outlined: https://drift.simonbinder.eu/Migrations/#guided-migrations

This is my `build.yaml`, to which I added the `databases` key.
```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
              version:
                "3.45.0"
          store_date_time_values_as_text: true
          generate_manager: false
          databases:
            xxx_database: lib/data/xxx_database.dart
        generate_for:
          include:
            - "lib/data/**"
            - "test/test_utils.dart"
```
Then I ran `dart run drift_dev make-migrations`

Then, I moved all of my previously generated schema files into the `drift_schemas/xxx_database` folder. I have these `json` files for versions from `v62` up to the new version, which is `v73` (which is just generated by `drift_dev`).

In `test/drift/xxx_database` there is a folder `generated` with schema files, as well as `migration_test.dart`.

I notice that it has the following import:
```dart
import 'package:xxx/data\xxx_database.dart';
```
With a `\`, which is obviously not going to work. It looks like there is some Windows issue going on.

When I change this `\` to a `/`, that part works again, but scrolling down, I get the following code:
```dart
    await verifier.testWithDataIntegrity(
      oldVersion: 62,
      newVersion: 63,
      createOld: v1.DatabaseAtV62.new,
      createNew: v2.DatabaseAtV63.new,
      ...
```
Where `v1` and `v2` could not be found (and I find it a bit strange that it does recongize the version numbers for `oldVersion` and `newVersion`, but not for the `create...` functions. The imports look as follows:
```dart
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations.dart';
import 'package:xxx/data/xxx_database.dart'; // <-- Where I already changed the backslash in this line
import 'package:test/test.dart';
import 'generated/schema.dart';

import 'generated/schema_v62.dart' as v62;
import 'generated/schema_v63.dart' as v63;
```

I don't have a schema JSON for these older versions. Additionally, it looks like these tests are only generated for `v62` to `v63`, none of the other schemas are imported (though their `.dart` files are present in the `test/drift/xxx_database/generated` folder).

Am I somehow able to use these guided migrations anyways? Or am I stuck using the manual process instead?
## Flutter doctor
```
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.22631.4460], locale nl-NL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.95.3)
[√] Connected device (3 available)
[√] Network resources
```
## Drift versions
```yaml
drift: ^2.21.0
build_runner: ^2.4.13
drift_dev: ^2.21.2
```
