### ISSUE TITLE
Android: MissingPluginException(No implementation found for method openDatabase on channel com.davidmartos96.sqflite_sqlcipher)

### ISSUE THREAD

**Issue by Beurni** [simolus3/moor#3377]
I use the encrypted_drift package to encrypt my database but for some reason when launching the app on Android it's throwing this no implementation exception. It is working fine on iOS though.

I added the these packages to my pubspec.yaml
```
  encrypted_drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/encryption

  drift: ^2.22.1

  drift_flutter: ^0.1.0

  path_provider: ^2.1.5
```

I already tried to relaunch the app and used the flutter clean command but it doesn't seem to work.

Im using Flutter 3.2.24 in case that is important. Help would be much appreciated.
