### ISSUE TITLE
Not support @TableIndex() to create Index with Postgresql

### ISSUE THREAD

**Issue by wild-coffee** [simolus3/moor#3391]
**Describe the bug**

Use @TableIndex() on table defination, with postgresql, call: createAll() failed!

error message: 

Failed assertion: line 36 pos 7: 'sql.containsKey(dialect)': Tried running SQL optimized for the following dialects: Closure: ([String]) => String from Function 'join':.. However, the database is running SqlDialect.postgres. Has that dialect been added to the `dialects` drift builder option?

drift version : 2.22.1

callstack:

```
'package:drift/src/runtime/query_builder/helpers.dart': Failed assertion: line 36 pos 7: 'sql.containsKey(dialect)': Tried running SQL optimized for the following dialects: Closure: ([String]) => String from Function 'join':.. However, the database is running SqlDialect.postgres. Has that dialect been added to the `dialects` drift builder option?
dart:core                                                      _AssertionError._throwNew
package:drift/src/runtime/query_builder/helpers.dart 36:7      WriteDefinition.pickForDialect
helpers.dart:36
package:drift/src/runtime/query_builder/migration.dart 544:38  Migrator._issueQueryByDialect
migration.dart:544
package:drift/src/runtime/query_builder/migration.dart 402:12  Migrator.createIndex
migration.dart:402
package:drift/src/runtime/query_builder/migration.dart 92:13   Migrator.create
migration.dart:92
package:drift/src/runtime/query_builder/migration.dart 80:13   Migrator.createAll
```

build.yaml
```
targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: postgres
          store_date_time_values_as_text: true
          databases:
            pg_database: bin/postgres_db/database.dart
```

order table source:
```
@TableIndex(name: 'idx_preparer', columns: {#preparer})
class Order extends Table
{
        TextColumn get preparer => text().references(Account, #id)();
}
```

**Comment by simolus3** [comment]
Thanks for the report! This is a bug in `drift_dev` when generating code. As a workaround for this, you can enable a second dialect even if you don't need it:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialects:
              - sqlite
              - postgres
          store_date_time_values_as_text: true
          databases:
            pg_database: bin/postgres_db/database.dart
```
