### ISSUE TITLE
cannot prefetch references if we use modules

### ISSUE THREAD

**Issue by michelemazzei** [simolus3/moor#3398]
**Cannot prefetch references if we use modules** 

Hi, I cannot access to prefetched references if I use drift_dev:modular manually.
If you build  the following code, it works fine without build.yaml and without drift  modular : 

```
import 'package:drift/drift.dart';
part 'db.g.dart';

class Tsid {
  final BigInt value;

  const Tsid(this.value);
}

class TsidTypeConverter extends TypeConverter<Tsid, BigInt> {
  const TsidTypeConverter();

  @override
  Tsid fromSql(BigInt fromDb) {
    return Tsid(fromDb);
  }

  @override
  BigInt toSql(Tsid value) {
    return value.value;
  }
}

@DriftAccessor(tables: [
  DynamicRelations,
  DynamicTableProperties,
])
class DynamicDatabaseDao extends DatabaseAccessor<Database>
    with $DynamicDatabaseDaoMixin {
  DynamicDatabaseDao(super.attachedDatabase);

  $$DynamicRelationsTableTableManager get relationsManager =>
      attachedDatabase.managers.dynamicRelations;

  Future<DynamicTableProperty?> getRelation(Tsid relationId) => relationsManager
      .withReferences()
      .filter((f) => f.id.equals(relationId))
      .getSingle()
      .then((value) => value.$2.sourcePropertyId.getSingle());
}

class DynamicRelations extends Table {
  Int64Column get id => int64().map(const TsidTypeConverter())();

  Int64Column get sourcePropertyId => int64()
      .map(const TsidTypeConverter())
      .references(DynamicTableProperties, #id)();

  Int64Column get targetPropertyId => int64()
      .map(const TsidTypeConverter())
      .references(DynamicTableProperties, #id)();

  DateTimeColumn get creationDate =>
      dateTime().withDefault(currentDateAndTime)();

  @override
  String get tableName => 'dynamic_database__dynamic_relations';

  @override
  Set<Column<Object>>? get primaryKey => {id};
}

class DynamicTableProperties extends Table {
  Int64Column get id => int64().map(const TsidTypeConverter())();

  TextColumn get name => text()();

  Int64Column get tableId => int64().map(const TsidTypeConverter())();

  @override
  Set<Column<Object>>? get primaryKey => {id};

  @override
  List<Set<Column<Object>>>? get uniqueKeys => [
        {name, tableId}
      ];

  @override
  String get tableName => 'dynamic_database__properties_names';
}

@DriftDatabase(tables: [
  DynamicRelations,
  DynamicTableProperties,
], daos: [
  DynamicDatabaseDao
], views: [])
abstract class Database extends $Database {
  final String databaseName;

  Database({
    required this.databaseName,
    required QueryExecutor executor,
  }) : super(executor);

  @override
  int get schemaVersion => 1;
}
```
 pubspec.yaml is:
```
dependencies:
  flutter:
    sdk: flutter

  drift: ^2.23.0
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  drift_dev: ^2.23.0
  build_runner: ^2.4.14
```

Now, if in the project we want to use drift dev modular configuration, like this: 

```
targets:
  $default:
    builders:
      drift_dev:
        # disable drift's default builder, we're using the modular setup
        # instead.
        enabled: false

      # Instead, enable drift_dev:analyzer and drift_dev:modular manually:
      drift_dev:analyzer:
        enabled: true
        options: &options
          # Drift build options, as per https://drift.simonbinder.eu/docs/advanced-features/builder_options/
          store_date_time_values_as_text: true
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.39"
              modules: [fts5]
      drift_dev:modular:
        enabled: true
        # We use yaml anchors to give the two builders the same options
        options: *options

```

And in the db.dart file we will change the
`part 'db.g.dart'` 

with : 

`import db.drift.dart
`

We will have the following error code : 

**The getter 'sourcePropertyId' isn't defined for the type 'BaseReferences<GeneratedDatabase, $DynamicRelationsTable, DynamicRelation>'.
Try importing the library that defines 'sourcePropertyId', correcting the name to the name of an existing getter, or defining a getter or field named 'sourcePropertyId'.**

Errore detected in the following line (sourcePropertyId is the problem): 
```
  Future<DynamicTableProperty?> getRelation(Tsid relationId) => relationsManager
      .withReferences()
      .filter((f) => f.id.equals(relationId))
      .getSingle()
      .then((value) => value.$2.sourcePropertyId.getSingle());

```

Any idea/suggestion?
Thank you
