### ISSUE TITLE
[drift_dev] Flutter not resolving

### ISSUE THREAD

**Issue by rubenvde** [simolus3/moor#3424]
Flutter is not resolving because drift_dev still depends on analyzer 6.4.1, but analyzer 7 is already out for 2 months:

```
Because freezed >=2.5.8 <3.0.0-0.0.dev depends on analyzer ^7.0.0 and drift_dev 2.23.1 depends on analyzer ^6.4.1, freezed >=2.5.8 <3.0.0-0.0.dev is incompatible with drift_dev 2.23.1.
And because no versions of drift_dev match >2.23.1 <3.0.0, freezed >=2.5.8 <3.0.0-0.0.dev is incompatible with drift_dev ^2.23.1.
So, because <my_project> depends on both drift_dev ^2.23.1 and freezed ^2.5.8, version solving failed.
```
Looks like #3024 is pretty similar but for another version.

**Comment by simolus3** [comment]
Thanks for the report! We generally try to support the latest two stable Flutter versions (and in the case of `analyzer`, it was impossible to support the latest version which contains breaking change while keeping compatibility with those older versions).

Obviously, when we get to the point where we start being incompatible with other packages that have moved on to newer versions, we should upgrade too. 

As an immediate workaround, you can add this to your pubspec:

```yaml
dependency_overrides:
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: support-analyzer-7
```

I'll get this released ~~later today~~ tomorrow, apparently.
