### ISSUE TITLE
Manager references not being generated if table classes are in different files

### ISSUE THREAD

**Issue by marcelomendoncasoares** [simolus3/moor#3446]
**Describe the bug**

If two referenced classes are in different files, the reversed references between them are not being generated. It only works if the classes belong to the same file. The bug is happening when using the modular build mode and regardless of the `ReferenceName` annotation.

If the two classes are in the same file, the references are correctly generated. The expected behavior is that the references gets generated regardless of where the class is defined.

**How to reproduce**

1. Create a file named `users.dart` with the `Users` table:
```dart
import 'package:drift/drift.dart';

class Users extends Table {
  late final id = integer().autoIncrement()();
  late final name = text()();
}
```

2. Create a file named `groups.dart` with the `Groups` table:
```dart
import 'package:drift/drift.dart';

import 'users.dart';

class Groups extends Table {
  late final id = integer().autoIncrement()();
  late final name = text()();
  @ReferenceName('administeredGroups')
  late final admin = integer().nullable().references(Users, #id)();
  @ReferenceName('ownedGroups')
  late final owner = integer().references(Users, #id)();
}
```

3. Check the `users.drift.dart` file to see that the `administeredGroups` and `ownedGroups` references does not exist.
4. When trying to create a filter on the `AppDatabase`, check that the `ownedGroups` does not exist indeed.
```dart
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import 'groups.dart';
import 'users.dart';
import 'users.drift.dart';
import 'database.drift.dart';

@DriftDatabase(
  tables: [
    Users,
    Groups,
  ],
)
class AppDatabase extends $AppDatabase {
  AppDatabase() : super(_openConnection());

  Future<List<User>> getOwners(String groupName) async {
    return managers.users
        .filter((f) => f.ownedGroups((g) => g.name.equals(groupName)))  // This will fail with undefined method
        .get();
  }

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON');
      },
    );
  }

  /// Stores the database in `getApplicationDocumentsDirectory()`.
  static QueryExecutor _openConnection() {
    return driftDatabase(name: 'database');
  }
}
```
The error will be:
> The method 'ownedGroups' isn't defined for the type '$$UsersTableFilterComposer'.
> Try correcting the name to the name of an existing method, or defining a method named 'ownedGroups'

5. Move the `Groups` class to the `users.dart` file, remove the `import 'groups.dart';` line from the above code and run the builder again to see error disappear.

**Build config**
The following build config is being used on drift version 2.24. It was not tested with other build configurations.
```yaml
targets:
  # Configure the Drift to build in modular mode instead of shared.
  # https://drift.simonbinder.eu/generation_options/modular/#enabling-modular-code-generation
  drift:
    auto_apply_builders: false
    builders:
      drift_dev:analyzer:
        enabled: true
        options: &options
          store_date_time_values_as_text: true
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.46"
              modules:
                - dbstat
                - fts5
                - json1
                - math
          databases:
            main_database: lib/database.dart
      drift_dev:modular:
        enabled: true
        options: *options

  $default:
    dependencies:
      # Run drift's builder first
      - ":drift"
    builders:
      # Disable default drift builder to use the modular builder instead.
      drift_dev:
        enabled: false
```
