### ISSUE TITLE
Drift generates wrong expression for dateTime().withDefault(currentDateAndTime)() in migrations schema

### ISSUE THREAD

**Issue by shehabmohamed0** [simolus3/moor#3462]
I am using drift migration tests 

The tests keeps failing with 
Schema does not match
drift_video_downloads:
 columns:
  created_at:
   Not equal: `NOT NULL DEFAULT (CAST(strftime('%s', CURRENT_TIMESTAMP) AS INTEGER))` (expected) and `NOT NULL DEFAULT (CURRENT_TIMESTAMP)` (actual)

although I did not change created_at column 

I am using these build options 
```
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          databases:
            # Required: A name for the database and it's path
            my_database: lib/core/data/database/database.dart
```

I want to store date time as text by setting  store_date_time_values_as_text to true

when I reviewed the generated schema files from previos versions I found that it is like that 
```
 {
    "name": "created_at",
    "getter_name": "createdAt",   
    "moor_type": "dateTime",
    "nullable": false,
    "customConstraints": null,
    "default_dart": "const CustomExpression('CAST(strftime(\\'%s\\', CURRENT_TIMESTAMP) AS INTEGER)')",
    "default_client_dart": null,
    "dsl_features": []
},

"default_dart": "const CustomExpression('CAST(strftime(\\'%s\\', CURRENT_TIMESTAMP) AS INTEGER)')",
```

cusstom expression is set to integer type regarding store_date_time_values_as_text set to true 
shouldn't it be  CURRENT_TIMESTAMP only ?

**Comment by simolus3** [comment]
> I am using these build options

To clarify, did you change the `store_date_time_values_as_text` value at some point? If you initially used the integer-based format to store date time values and later change that option, you need to [write a migration](https://drift.simonbinder.eu/guides/datetime-migrations/#to-text) for that.

The `default_dart` value in the earlier schema files is supposed to represent what `store_date_time_values_as_text` indicated at the time that schema was exported. This is a good thing, since your users with an older version of the app also have a integer values in their databases, so an explicit migration is required.

**Comment by shehabmohamed0** [comment]
Not I have not changed it It's store_date_time_values_as_text : true from the beginning 

The problem is only with the generated schema for tests not from the actual database it self

**Comment by simolus3** [comment]
Thanks, after taking another look I can confirm that this is actually a regression in `drift_dev`. I've fixed this in 342820325c60f71972f0c462bde30c3892f4e92c. Could you add this `dependency_override` to your `pubspec.yaml` and try exporting the schem again?

```yaml
dependency_overrides:
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
```
