### ISSUE TITLE
Wrong Insertable generation

### ISSUE THREAD

**Issue by AlexDochioiu** [simolus3/moor#3463]
**Describe the bug**

<img width="1162" alt="Image" src="https://github.com/user-attachments/assets/b34d0615-89b3-4d57-8407-e7e9631b4802" />

<img width="648" alt="Image" src="https://github.com/user-attachments/assets/7862937f-7dad-42aa-a223-4b783f8b4c6e" />

-- Recently, the code-gen just wiped all of my correct insertable generation(s) and replaced them with a wrong/empty implementation.

**Comment by AlexDochioiu** [comment]
Note: Changing and using `write_to_columns_mixins: true` instead of `toInsertable` seems to work. The mixins are correct.

**Comment by simolus3** [comment]
Thanks for the report, could you also post the definition of the table class and the custom row class you're using with that table?

**Comment by AlexDochioiu** [comment]
Sharing one example that's smaller (but suffering from the same issue). 

Note: Using `late final` or getter for the columns makes no difference.

```dart
import "dart:convert";

import "package:cardano_dart_types/cardano_dart_types.dart";
import "package:drift/drift.dart" hide JsonKey;
import "package:freezed_annotation/freezed_annotation.dart";

import "../../utils/binary/marshalable.dart";
import "../../utils/sugar_dart.dart";
import "../database_impl/vespr_database_impl.vm.dart";

part "contact.freezed.dart";
part "contact.g.dart";

@UseRowClass(Contact, generateInsertable: true)
class ContactTable extends Table {
  late final TextColumn internalUid = text()();
  late final TextColumn address = text()();
  late final TextColumn label = text()();
  late final TextColumn adaHandle = text().nullable()();

  @override
  bool get withoutRowId => true;

  @override
  Set<Column>? get primaryKey => {internalUid};
}

@freezed
class Contact with _$Contact implements Marshalable {
  static const int mTypeId = 22;
  factory Contact({
    required String internalUid,
    required String address,
    required String label,
    required String? adaHandle,
  }) = _Contact;
  Contact._();

  late final Lazy<String?> initial = Lazy(
    () {
      final inital = label.take(1);
      if (inital.isNotEmpty) {
        return inital.toUpperCase();
      } else {
        return null;
      }
    },
  );

  late final Lazy<String> ellipsizedAddress = Lazy(() => address.ellipsizeMiddle(20));

  late final Lazy<bool> labelIsHandle = Lazy(() => adaHandle != null && "\$$adaHandle" == label);

  @override
  Uint8List marshal() => jsonEncode(toJson()).utf8Decode();

  factory Contact.fromJson(Map<String, dynamic> json) => _$ContactFromJson(json);

  static Contact unmarshal(Uint8List data) {
    final jsonString = data.utf8Encode();
    final contactMap = jsonDecode(jsonString) as Map;
    return Contact.fromJson(contactMap.cast());
  }

  @override
  int get typeId => mTypeId;
}

```

**Comment by simolus3** [comment]
Thanks. Also, do you have something in your `build.yaml` (if you have that file at all) that would make freezed run before `drift_dev`? Not sure if that alone fixes the problem though, I'll have to try.

**Comment by AlexDochioiu** [comment]
### The build.yaml when the issue was identified
```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          explicit_to_json: true
      freezed:
        options:
          format: false
          map: false
          when: false

```

#### Also, the yaml after changing to use mixin (which works fine)
```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          write_to_columns_mixins: true 
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          explicit_to_json: true
      freezed:
        options:
          format: false
          map: false
          when: false
```

**Comment by simolus3** [comment]
This is a regression from when we started tracking which columns are actually available on custom row classes to fix other generation issues. When we check for available columns as fields, we didn't consider inherited fields.
I've fixed this on `develop`, you'll have to use the [version from git](https://drift.simonbinder.eu/Internals/#using-an-unreleased-drift-version) (at least for `drift_dev`) until the fix is released.

In addition to the dependency override, you'll have to change your `build.yaml` to guarantee that `freezed` runs before `drift`:

```yaml
targets:
  freezed:
    auto_apply_builders: false
    builders:
      freezed:
        enabled: true
        options:
          format: false
          map: false
          when: false
  $default:
    dependencies: [':freezed']
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          explicit_to_json: true
      freezed:
        enabled: false # Already runs in the other target
```
