### ISSUE TITLE
Generator prints warning when using json_object inside .drift files

### ISSUE THREAD

**Issue by saibotma** [simolus3/moor#3497]
**Description**

The generator prints the following warnings when generating code for the below `.drift` file, and I don't know how to get rid of it:

```
[WARNING] drift_dev on lib/shared/database/database.dart:
line 11, column 12: Function json_object could not be found
   ╷
11 │     SELECT json_object('id', 'test');
   │            ^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/shared/database/database.dart:
line 11, column 12: Expression has an unknown type, the generated code can be inaccurate.
   ╷
11 │     SELECT json_object('id', 'test');
   │            ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵

```

`get_json.drift`:
```
getJson:
    SELECT json_object('id', 'test');
```

**Versions**

drift: 2.26.0
drift_dev: 2.26.0
dart: 3.6.2

**Comment by simolus3** [comment]
Drift supports analyzing json functions like `json_object`, but it makes conservative assumptions about the sqlite3 version you actually get at runtime. In this case, it assumes that you have an old sqlite3 version without the `json1` module. You can create [a build configuration](https://drift.simonbinder.eu/generation_options/#assumed-sql-environment) to tell drift that it's safe to assume that you'll have a more recent version available, e.g. with

```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialects:
              - sqlite
              - postgres
            options:
              version: "3.38"
```
