### ISSUE TITLE
Generador de código de Drift

### ISSUE THREAD

**Issue by edgardo999** [simolus3/moor#3522]
Resumen del Problema:

El generador de código de Drift (drift_dev) parece estar generando incorrectamente la parte de app_database.g.dart que proporciona acceso a los DAOs listados en la anotación @DriftDatabase. Específicamente, en lugar de generar getters que devuelvan la instancia concreta del DAO (que usa el mixin _$XxxDaoMixin), genera código que intenta instanciar directamente la clase DAO abstracta (ej., late final RecipeDao recipeDao = RecipeDao(this as AppDatabase);), lo cual causa un error de compilación porque las clases abstractas no pueden ser instanciadas.

Este problema persiste a pesar de que:

Las definiciones de la base de datos (AppDatabase) y los DAOs (RecipeDao, etc.) parecen seguir las convenciones de Drift (clases abstractas, extends DatabaseAccessor, directiva part, constructor correcto, anotación @DriftAccessor).
La anotación @DriftDatabase en AppDatabase lista correctamente las tablas y los DAOs.
Se resolvieron conflictos de nombres renombrando modelos de dominio manuales.
Se realizaron múltiples limpiezas (flutter clean, borrado manual de .dart_tool y build) y regeneraciones de código (flutter pub run build_runner build --delete-conflicting-outputs).
Las versiones de drift, drift_dev y build_runner parecen compatibles.
Pasos Intentados (sin éxito para este problema específico):

Resolver conflictos de dependencias (async).
Ajustar configuración de Gradle (compileSdk, signingConfigs).
Aceptar licencias de Android.
Renombrar modelos de dominio (Recipe -> RecipeModel, etc.).
Verificar y corregir definiciones de DAO (quitar/restaurar with _$...Mixin, quitar/restaurar constructores).
Verificar y corregir la anotación @DriftDatabase (quitar/restaurar lista daos:).
Verificar el Service Locator (get_it).
Realizar flutter clean, borrar .dart_tool, borrar build.
Ejecutar flutter pub get.
Ejecutar flutter pub run build_runner build --delete-conflicting-outputs múltiples veces.
Verificar versiones de paquetes en pubspec.lock.
Intentar fijar versiones de drift y drift_dev.
Código Relevante:

pubspec.yaml (Dependencias):

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fake_async: 1.3.2
  async: ^2.12.0 # Fijado por flutter_test
  permission_handler: ^11.3.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  go_router: ^14.2.1 # (Versión actual en lockfile: 14.8.1)
  drift: 2.18.0 # Fijado a 2.18.0 (anteriormente ^2.18.0, resuelto a 2.26.0)
  sqlite3_flutter_libs: ^0.5.22 # (Versión actual en lockfile: 0.5.32)
  path_provider: ^2.1.3 # (Versión actual en lockfile: 2.1.5)
  path: ^1.9.0 # (Versión actual en lockfile: 1.9.1)
  dio: ^5.5.0+1 # (Versión actual en lockfile: 5.8.0+1)
  get_it: ^8.0.3
  flutter_local_notifications: ^19.0.0
  equatable: ^2.0.5 # (Versión actual en lockfile: 2.0.7)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: 2.18.0 # Fijado a 2.18.0 (anteriormente ^2.18.0, resuelto a 2.26.0)
  build_runner: ^2.4.11 # (Versión actual en lockfile: 2.4.15)
```

lib/data/local/app_database.dart (Estado actual):

```
import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';
import 'dao/recipe_dao.dart';
import 'dao/recipe_category_dao.dart';
import 'dao/recipe_ingredient_dao.dart';
import 'dao/recipe_category_relation_dao.dart';
import 'dao/favorite_recipe_dao.dart';

part 'app_database.g.dart';

// --- Definiciones de Tablas ---
class Recipes extends Table { ... }
class RecipeCategories extends Table { ... }
class RecipeIngredients extends Table { ... }
class RecipeCategoryRelations extends Table { ... }
class FavoriteRecipes extends Table { ... }

// --- Definición de la Base de Datos ---
@DriftDatabase(
  tables: [
    Recipes,
    RecipeCategories,
    RecipeIngredients,
    RecipeCategoryRelations,
    FavoriteRecipes
  ],
  daos: [ // La lista daos está presente
    RecipeDao,
    RecipeCategoryDao,
    RecipeIngredientDao,
    RecipeCategoryRelationDao,
    FavoriteRecipeDao
  ]
)
class AppDatabase extends _$AppDatabase {
  AppDatabase._internal() : super(_openConnection());
  static final AppDatabase instance = AppDatabase._internal();
  @override
  int get schemaVersion => 1;
}

LazyDatabase _openConnection() { ... }
lib/data/local/dao/recipe_dao.dart (Estado actual - ejemplo):

import 'package:drift/drift.dart';
import '../app_database.dart';

part 'recipe_dao.g.dart'; // Directiva part presente

@DriftAccessor(tables: [Recipes])
abstract class RecipeDao extends DatabaseAccessor<AppDatabase> { // Sin 'with'
  // Constructor presente
  RecipeDao(AppDatabase db) : super(db);

  Future<List<Recipe>> getAllRecipes() => select(db.recipes).get();
  // ... otros métodos ...
}
Fragmento incorrecto generado en lib/data/local/app_database.g.dart:

// Esto es lo que se genera incorrectamente:
late final RecipeDao recipeDao = RecipeDao(this as AppDatabase);
late final RecipeCategoryDao recipeCategoryDao = RecipeCategoryDao(this as AppDatabase);
// ... etc ...

// Esto es lo que se esperaría (aproximadamente):
// late final RecipeDao recipeDao = _$RecipeDao(this);
// late final RecipeCategoryDao recipeCategoryDao = _$RecipeCategoryDao(this);
Último error de compilación:

lib/data/local/app_database.g.dart:xxxx:xx: Error: The class 'RecipeDao' is abstract and can't be instantiated.
  late final RecipeDao recipeDao = RecipeDao(this as AppDatabase);
                                   ^^^^^^^^^
```
(Errores similares para los otros DAOs)
Información Adicional Sugerida para el Reporte:

Versión de Flutter (flutter --version)
Flutter 3.29.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c236373904 (4 weeks ago) • 2025-03-13 16:17:06 -0400       
Engine • revision 18b71d647a
Tools • Dart 3.7.2 • DevTools 2.42.3

Windows 10 64 bits
