### ISSUE TITLE
Problems with Modular Generation

### ISSUE THREAD

**Issue by euregon-Harzenetter** [simolus3/moor#3563]
Hi there

im quite new to drift and cant figure it out with the help of the documentation. 

I got the following Problem: 
I already got a working (and filled) database from an old version of my app. The current schema of the database is imported to drift via SQL-Schema (contains only CREATE TABLE Statements), because it already exists and has >150 tables. Therefore is the generated _database.g.dart_ File quite large (~95k lines). So obviously i tried the modular generation to avoid this. But with the following build.yaml it still only generates one large file. 

Am i missing something important in the build-file or is it just not possible to use modular generation with an SQL-Schema as basis. 

Any Help would be apprechiated.

Database.dart
```
import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/services.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:drift_sqflite/drift_sqflite.dart';
import 'package:sqflite_sqlcipher/sqflite.dart';

part 'database.g.dart';

@DriftDatabase(include:{'schema.drift'})
class Database extends _$Database {

  Database() : super(_openConnection());

  @override
  int get schemaVersion => 7351;

  static QueryExecutor _openConnection() {
    return SqfliteQueryExecutor.inDatabaseFolder(path: 'database');
  }
}
```

build.yaml
```
targets:
  $default:
    builders:
      drift_dev:
        enabled: false
      drift_dev:analyzer:
        enabled: true
        options: &options
          databases:
            my_database: lib/data/drift-testing-lib/Database.dart
          store_date_time_values_as_text: true
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.39"
              modules: [fts5]
      drift_dev:modular:
        enabled: true
        options: *options
```

a part of my schema.drift
```
create table Arzt (
arztID               INTEGER              not null,
name                 TEXT                 not null  collate nocase,
vorname              TEXT                 not null  collate nocase,
telefon              TEXT                   collate nocase,
telefon2             TEXT                   collate nocase,
fax                  TEXT                   collate nocase,
strasse              TEXT                   collate nocase,
plz                  TEXT                   collate nocase,
ort                  TEXT                   collate nocase,
fachgebiet           TEXT                   collate nocase,
info                 TEXT,
primary key (arztID)
);

create table ArztAbwesenheit (
arztAbwesenheitID    INTEGER              not null,
arztID               INTEGER              not null,
vertretungsarztID    INTEGER,
von                  TEXT                 not null,
bis                  TEXT                 not null,
grund                TEXT                 not null,
bemerkung            TEXT,
primary key (arztAbwesenheitID),
constraint FK_ArztAbwesenheit_Arzt foreign key (arztID)
   references Arzt (arztID)
      on delete cascade on update restrict,
constraint FK_ArztAbwesenheit_Arzt foreign key (vertretungsarztID)
   references Arzt (arztID)
      on delete restrict on update restrict
);

....
```
