### ISSUE TITLE
Feature request: refresh button in drift_ext when viewing a table

### ISSUE THREAD

**Issue by ghost-458** [simolus3/moor#3578]
**Description**

It would be nice to have a button to refresh table data when inspecting a table's rows. I'm currently having to press the back button `<-` out of a table, then press the table again to reload the data. 

**Versions**

```
  drift:
    dependency: "direct main"
    description:
      name: drift
      sha256: af3941e4d544727b2eb80590eb64e9cb8d77cd68c7690265502ea6a2427aa621
      url: "https://pub.dev"
    source: hosted
    version: "2.23.1"
  drift_dev:
    dependency: "direct main"
    description:
      name: drift_dev
      sha256: fa98fdbb7303a1b5b2dc110cb516eda2253a5d291680f8cbc72b1af24099f7f9
      url: "https://pub.dev"
    source: hosted
    version: "2.23.1"
  drift_flutter:
    dependency: "direct main"
    description:
      name: drift_flutter
      sha256: "0cadbf3b8733409a6cf61d18ba2e94e149df81df7de26f48ae0695b48fd71922"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.4"
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/bfeb6f98-a941-4efc-b6ff-be3c7acdcbfc)

**Aditional info**

N/A
