### ISSUE TITLE
Flutter release 3.33 (beta) doesn't have macros, may cause drift to downgrade to 2.21

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/moor#3579]
We are mostly programming in Flutter Beta to come ahead of what is expected. 

In this particular version (at time of writing 3.33.0-0.2.pre) doesn't seem to suppport macros, and macros are announced deprecated https://dart.dev/language/macros 

This causes drift to "downgrade" to 2.21 (was previous 2.26) in our projects.

Will this matter be resolved soon ?

**Comment by simolus3** [comment]
Drift doesn't depend on macros. If you add an explicit dependency on `drift: ^2.26.1` and run `dart pub get`, you should get an error explaining why the resolution has failed. Could you share that?

**Comment by RoarGronmo** [comment]
Somehow the drift_dev does not get upgraded to 2.26.1 (it lands on 2.26.0, I think the aad_oauth package is to blame for that.., since it relies on dependencies which doesn't comply with 2.26.1 of drift_dev)...

I will check that in detail tomorrow...

**Comment by RoarGronmo** [comment]
Flutter 3.32.2 stable:

Current working pubspec.yaml
```
name: mwork
description: A tool for handling orders in Norva24.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+111

environment:
  #sdk: ">=2.16.0-80.1.beta <4.0.0"
  #sdk: ">=2.17.0 <4.0.0"
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter



  #_fe_analyzer_shared: 51.0.0
  #analyzer: ^6.2.0
  #camera_web: ^0.3.0
  #characters: ^1.4.0
  #material_color_utilities: ^0.1.5

  #webview_flutter: 4.0.1

  #build_runner: 2.4.14



  #flutter_webview_plugin:
  #  git: https://github.com/nuc134r/flutter_webview_plugin.git

  msal_js: ^2.14.0

  #--- aad-oauth Azure Active Directory login by Earlybyte ---
  aad_oauth: ^1.0.1
  #aad_oauth:
  #  git: https://github.com/Earlybyte/aad_oauth.git


  provider: ^6.0.3
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  #introduction_screen: ^3.0.2
  intl: ^0.20.2
  #socket_io_client: ^2.0.0-beta.4-nullsafety.0


  #--jwt--- makes it possible to analyze jwt
  jwt_decode: ^0.3.1

  #---Swagger changes---
  chopper: ^8.0.0
  json_annotation: ^4.5.0

  #---Google Maps---
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  google_static_maps_controller: ^1.0.0

  #---Pointer interceptor
  pointer_interceptor: ^0.10.0

  #---Location data (GPS)---
  #location: ^4.4.0
  #location: ^7.0.0
  #location_workspace:
  #  git:
  #    url: https://github.com/Lyokone/flutterlocation.git
  #    ref: master
  #location: ^7.0.1
  geolocator: ^14.0.0

  #---Get---
  get: ^4.6.5

  #---Flutter Bloc---
  flutter_bloc: ^9.0.0

  #---Settings / preferences ---
  #flutter_settings_screens: ^0.3.2-null-safety
  shared_preferences: ^2.2.1
  #pref: ^2.6.0

  #---Camera function---
  camera: ^0.11.0
  path_provider: ^2.0.15
  path: ^1.8.3

  #---image_picker function
  image_picker: ^1.0.2
  image_picker_for_web: ^3.0.0

  #---shimmer
  shimmer: ^3.0.0

  #---widget_zoom
  widget_zoom: ^0.0.4

  #---Floor functionality---
  #floor: ^1.2.0

  #---Drift functionality---
  drift: ^2.26.1
  #drift: ^2.20.0
  #drift:
  #  git:
  #    url: https://github.com/simolus3/drift.git
  #    ref: develop
  #    path: drift
  #drift: 1.7.1
  sqlite3_flutter_libs: ^0.5.7
  sqlite3: ^2.3.0


  #---Url launcher
  url_launcher: ^6.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  animated_rotating_widget: ^0.0.2

  #---badges for icons
  #badges: ^3.0.1

  #---flutter webview plugin displace
  #flutter_webview_plugin:
  #    git: https://github.com/nuc134r/flutter_webview_plugin.git

  #---logging:
  logging: ^1.0.2
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  #firebase_core_web: 2.10.0
  #web: 0.3.0
  #package_info_plus: ^5.0.0
  package_info_plus: ^8.0.0
  firebase_performance: ^0.10.0

  #---db_inspector
  drift_db_viewer: ^2.0.0

  #---validators
  email_validator: ^3.0.0

  #---list extensions
  collection: ^1.16.0

  #---flag
  flag: ^7.0.0

  #---data table 2
  data_table_2: ^2.4.2

  #---device info plus
  #device_info_plus: ^10.0.0
  device_info_plus: ^11.1.0
  label_marker: ^1.0.1
  custom_info_window: ^1.0.1

  #---file picker
  file_picker: ^10.0.0

  #---flutter_resizable_container:
  flutter_resizable_container: ^4.0.0-beta.3

  #---universal
  universal_html: ^2.2.4

  #---web
  web: ^1.0.0
  #web: ^1.0.0

  #---http
  http: ^1.1.0
  http_parser: ^4.0.1

  #---dio
  dio: ^5.3.2

  #---exif
  exif: ^3.1.4

  #---in_app_update
  in_app_update: ^4.2.3
  firebase_analytics: ^11.1.0

  #---reflectable:
  #reflectable: ^4.0.0
  #js: 0.7.1

  #---flutter_media_metadata
  #flutter_media_metadata: 1.0.0+1

  #---date_util
  #date_util: 0.1.4

  #---flutter_native_splash
  #flutter_native_splash: ^2.2.16


  #---Animated splashscreen:
  #animated_splash_screen: ^1.3.0
#---Icons---


#dependency_overrides:
  #camera_android_camerax: 0.6.10+2  #Workaroound for D8/R8 camera bug
  #camera_android_camerax: 0.6.11 #Workaround for camera tilt bug introduced in v0.6.12
  #intl: ^0.20.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_round.png"
  adaptive_icon_background: "#666666"

dev_dependencies:
  flutter_test:
    sdk: flutter

  #---swagger changes---
  build_runner: ^2.1.11
  chopper_generator: ^8.0.0
  json_serializable: ^6.2.0
  swagger_dart_code_generator: ^3.0.0
  #swagger_dart_code_generator:
  #  git:
  #    url: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator.git
  #    ref: bacb7781f94e44cb217f163aee8cb681b40d55af


  #---Launcher icons---
  flutter_launcher_icons: ^0.14.1

  #---floor generators---
  #floor_generator: ^1.2.0

  #---drift generators---
  drift_dev: ^2.26.0
  #drift_dev: ^2.20.0
  #drift_dev: 1.7.1

  #--- analyzer
  #analyzer: ^7.3.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  #flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



```

With flutter stable release `v3.32.2` :

in pubspec.yaml:
...
`drift: ^2.26.1`
...
`drift_dev: ^2.26.0   #note minor release 0 !`

This causes no error messages, and the result is:
```
C:\FlutterProjects\mWork git:[dev_roar_2025_05_06_v1_0_2_112]
dart pub get
Resolving dependencies... 
Downloading packages... 
  _fe_analyzer_shared 76.0.0 (82.0.0 available)
  analyzer 6.11.0 (7.4.5 available)
  dart_style 2.3.8 (3.1.0 available)
  drift_dev 2.26.0 (2.26.1 available)
  flutter_secure_storage_linux 1.2.3 (2.0.1 available)
  flutter_secure_storage_macos 3.1.3 (4.0.0 available)
  flutter_secure_storage_platform_interface 1.1.2 (2.0.1 available)
  flutter_secure_storage_web 1.2.1 (2.0.0 available)
  flutter_secure_storage_windows 3.1.2 (4.0.0 available)
  js 0.6.7 (0.7.2 available)
  leak_tracker 10.0.9 (11.0.1 available)
  leak_tracker_flutter_testing 3.0.9 (3.0.10 available)
  leak_tracker_testing 3.0.1 (3.0.2 available)
  material_color_utilities 0.11.1 (0.13.0 available)
  meta 1.16.0 (1.17.0 available)
  test_api 0.7.4 (0.7.6 available)
  vector_math 2.1.4 (2.2.0 available)
  vm_service 15.0.0 (15.0.1 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
```

Rising `flutter_dev: ^2.26.1     #note minor release 1 !`

resulting in following error:

```
C:\FlutterProjects\mWork git:[dev_roar_2025_05_06_v1_0_2_112]
dart pub get
Resolving dependencies... (3.3s)
Because no versions of dart_style match >2.3.8 <3.0.0 and dart_style >=2.3.7 <2.3.8 depends on analyzer ^6.5.0, dart_style >=2.3.7 <2.3.8-∞ or >2.3.8 <3.0.0 requires analyzer ^6.5.0.
And because dart_style 2.3.8 depends on analyzer ^6.9.0 and swagger_dart_code_generator >=2.4.0-prerelease.4 depends on dart_style ^2.2.1, swagger_dart_code_generator >=2.4.0-prerelease.4 requires analyzer ^6.5.0 or dart_style >=2.2.1 <2.3.7.
And because drift_dev >=2.26.1 depends on analyzer ^7.3.0 and drift_dev >=2.23.0 depends on dart_style >=2.3.7 <4.0.0, drift_dev >=2.26.1 is incompatible with swagger_dart_code_generator >=2.4.0-prerelease.4.
So, because mwork depends on both swagger_dart_code_generator ^3.0.0 and drift_dev ^2.26.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on drift_dev: dart pub add dev:drift_dev:^2.26.0
```

I thought `aad_oauth` was to blame here, but now I see there may be other reasons.

Now I change the channel to beta ( in writing moment `v3.33.0-0.2.pre`): 

Trying the same as last with both on `2.26.1`, resulting in a slightly different message:
```
C:\FlutterProjects\mWork git:[dev_roar_2025_05_06_v1_0_2_112]
dart pub get
Resolving dependencies... (1.7s)
Because no versions of dart_style match >2.3.8 <3.0.0 and dart_style >=2.3.7 <2.3.8 depends on analyzer ^6.5.0, dart_style >=2.3.7 <2.3.8-∞ or >2.3.8 <3.0.0 requires analyzer ^6.5.0.
And because dart_style 2.3.8 depends on analyzer ^6.9.0 and swagger_dart_code_generator >=2.4.0-prerelease.4 depends on dart_style ^2.2.1, swagger_dart_code_generator >=2.4.0-prerelease.4 requires analyzer ^6.5.0 or dart_style >=2.2.1 <2.3.7.
And because drift_dev >=2.26.1 depends on analyzer ^7.3.0 and drift_dev >=2.23.0 depends on dart_style >=2.3.7 <4.0.0, drift_dev >=2.26.1 is incompatible with swagger_dart_code_generator >=2.4.0-prerelease.4.
So, because mwork depends on both swagger_dart_code_generator ^3.0.0 and drift_dev ^2.26.1, version solving failed.
```

This time there is no suggestion to downgrade `drift_dev` to `^2.26.0`...

Lowering the drift versions to 2.20.0 to see what is provided, note that this results 'cleans the sheets' from `flutter v3.32.2` and removes the `macros` and `_macros` dependencies, and in turn upgrades (and downgrades !) many others:

```
C:\FlutterProjects\mWork git:[dev_roar_2025_05_06_v1_0_2_112]
dart pub get
Resolving dependencies... (1.5s)
Downloading packages... (4.0s)
< _fe_analyzer_shared 67.0.0 (was 76.0.0) (82.0.0 available)
< analyzer 6.4.1 (was 6.11.0) (7.4.5 available)
+ analyzer_plugin 0.11.3 (0.13.1 available)
< build 2.4.1 (was 2.4.2) (2.4.2 available)
< build_resolvers 2.4.2 (was 2.4.4) (2.4.4 available)
< build_runner 2.4.13 (was 2.4.15) (2.4.15 available)
< build_runner_core 7.3.2 (was 8.0.0) (8.0.0 available)
< chopper_generator 8.0.3 (was 8.1.0) (8.1.0 available)
< dart_style 2.3.6 (was 2.3.8) (3.1.0 available)
< drift 2.21.0 (was 2.26.1) (2.26.1 available)
< drift_dev 2.21.2 (was 2.26.0) (2.26.1 available)
  flutter_secure_storage_linux 1.2.3 (2.0.1 available)
  flutter_secure_storage_macos 3.1.3 (4.0.0 available)
  flutter_secure_storage_platform_interface 1.1.2 (2.0.1 available)
  flutter_secure_storage_web 1.2.1 (2.0.0 available)
  flutter_secure_storage_windows 3.1.2 (4.0.0 available)
  js 0.6.7 (0.7.2 available)
< json_serializable 6.8.0 (was 6.9.5) (6.9.5 available)
> leak_tracker 11.0.1 (was 10.0.9)
> leak_tracker_flutter_testing 3.0.10 (was 3.0.9)
> leak_tracker_testing 3.0.2 (was 3.0.1)
  material_color_utilities 0.11.1 (0.13.0 available)                                                                                                                                                                                                             
  meta 1.16.0 (1.17.0 available)                                                                                                                                                                                                                                 
< shelf_web_socket 2.0.1 (was 3.0.0) (3.0.0 available)                                                                                                                                                                                                           
< source_gen 1.5.0 (was 2.0.0) (2.0.0 available)                                                                                                                                                                                                                 
< sqlparser 0.39.2 (was 0.41.0) (0.41.0 available)                                                                                                                                                                                                               
  test_api 0.7.4 (0.7.6 available)                                                                                                                                                                                                                               
  vector_math 2.1.4 (2.2.0 available)                                                                                                                                                                                                                            
  vm_service 15.0.0 (15.0.1 available)                                                                                                                                                                                                                           
These packages are no longer being depended on:
- _macros 0.3.3 from sdk dart
- macros 0.1.3-main.0
Changed 20 dependencies!
26 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
```

Note the lines above on `drift` and `drift_dev` which is downgraded to `2.21.0` and `2.21.2` respectively.

At this level it will work, but in the strange way that it has lowered its versions.

---

I am sorry that I blamed you using macros here (I should have checked better), but it was tempting to do so, since that was the dependency which was removed.

I see that we need to dive deeper here and do some considerations on use of "outdated" dependecies, to rise the level of other dependencies such as `analyzer`.

It is sadly the culprit of Flutter/Dart... ...the "Dependency Hog" 

Hog = Marslands, Wetlands, which may be dangerous to walk in to if don't now where you go...
