### ISSUE TITLE
`.steps.dart` file not including source_gen preamble

### ISSUE THREAD

**Issue by Mr-Pepe** [simolus3/moor#3593]
My `build.yaml` contains

```yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          preamble:
            // coverage:ignore-file
```

but it seems that the code generator for `.steps.dart` files does not honor this setting.

Just wanted to raise this issue first and see if this is known or a <5 min fix for a maintainer, before I dive into the code.
