### ISSUE TITLE
Can't build Android app

### ISSUE THREAD

**Issue by ykaito21** [simolus3/moor#363]
I cannot build with this error. Is there any possible solution?

**Error:**
```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...

Abi 'MIPS' is not recognized in '/Users/kaii/Library/Android/sdk/ndk/21.0.6224779'.
Abi 'MIPS64' is not recognized in '/Users/kaii/Library/Android/sdk/ndk/21.0.6224779'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':moor_ffi:generateJsonModelDebug'.
> Build command failed.
  Error while executing process /Users/kaii/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/kaii/development/flutter/.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.3.2/android/cpp -B/Users/kaii/development/flutter/.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.3.2/android/.cxx/cmake/debug/armeabi -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-22 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/kaii/project/flutter/whatto/build/moor_ffi/intermediates/cmake/debug/obj/armeabi -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/Users/kaii/Library/Android/sdk/ndk/21.0.6113669 -DCMAKE_TOOLCHAIN_FILE=/Users/kaii/Library/Android/sdk/ndk/21.0.6113669/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/kaii/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja}
  -- Configuring incomplete, errors occurred!

  CMake Error at /Users/kaii/Library/Android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:104 (message):
    Could not find toolchain file:
    /Users/kaii/Library/Android/sdk/ndk/21.0.6113669/build/cmake/android.toolchain.cmake
  Call Stack (most recent call first):
    CMakeLists.txt:2 (project)
  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

**flutter doctor:**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)
```

**packages:**
```
  moor: ^2.3.0
  moor_ffi: ^0.3.2
  path_provider: ^1.5.1
  path: ^1.6.4

dev_dependencies:
  moor_generator: ^2.3.1
  build_runner: ^1.7.3
```

**Comment by simolus3** [comment]
Can you try adding the following to your pubspec, run `flutter clean` and then try again?
```yaml
dependency_overrides:
  moor_ffi:
    git:
      url: https://github.com/simolus3/moor.git
      ref: ndk-build
      path: moor_ffi
```
