### ISSUE TITLE
Trying out the latest changes from develop

### ISSUE THREAD

**Issue by Max-Might** [simolus3/moor#489]
Hello. I am trying to build my project with the latest code from the develop branch as explained but I get to types of errors in the generated code and the project can not be compiled.

The first one is that the `Variable` class now needs 2 type parameters:
```
org-dartlang-app:/models/database/database.g.dart:507:25: Error: Expected 1 type arguments.
      map['key_guid'] = Variable<String, StringType>(d.keyGuid.value);
                        ^
../../flutter/.pub-cache/git/moor-424c2febda6f7787c5bcce4bec7f2fa326f0130b/moor/lib/src/runtime/query_builder/expressions/variables.dart:19:9: Context: Found this candidate, but the arguments don't match.
  const Variable(this.value);
        ^^^^^^^^
```

The second one is about missing `db` property:
```
org-dartlang-app:/models/database/daos/jobs_dao.g.dart:19:42: Error: The getter 'db' isn't defined for the class '_$JobsDaoMixin'.
 - '_$JobsDaoMixin' is from 'package:xxx/models/database/daos/jobs_dao.dart' ('org-dartlang-app:/models/database/daos/jobs_dao.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'db'.
  $TicketEmailsTable get ticketEmails => db.ticketEmails;
                                         ^^
```

And here is how my pubspec file looks like:
```
name: xxx
description: xxx

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  intl: ^0.16.0
  rxdart: ^0.23.1
  moor_flutter: ^2.1.0
  get_it: ^3.1.0
  dio: ^3.0.8
  encrypt: ^4.0.0
  flutter_secure_storage: ^3.3.1+1
  toast: ^0.1.5
  battery: ^0.3.1+7
  rx_shared_preferences: ^1.1.1+1
  tuple: ^1.0.3
  flutter_date_pickers: ^0.0.6
  badges: ^1.1.0
  sprintf: ^4.0.2
  auto_size_text: ^2.1.0
  flutter_html: ^0.11.1
  device_info: ^0.4.1+4
  app_settings: ^2.0.0
  timezone: ^0.5.6
  get_version: ^0.2.1
  url_launcher: ^5.4.1
  image_picker: ^0.6.3+1
  path_provider: ^1.6.0
  open_file: ^3.0.1
  path: ^1.6.4
  crypto: ^2.1.3
  flutter_typeahead: ^1.8.0
  flutter_dialogs: 1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dependency_overrides:
  moor:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor
  moor_flutter:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor_flutter
  moor_generator:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor_generator
  sqlparser:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: sqlparser

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9
  moor_generator: ^2.3.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/i18n/

builders:
  moor_generator: ^2.3.1
  r_flutter: ^0.6.0

r_flutter:
  intl: lib/assets/i18n/en.arb

```

Am I doing something wrong or this is just the state of the develop branch at the moment?
