### ISSUE TITLE
Inserting objects without ID

### ISSUE THREAD

**Issue by dricholm** [simolus3/moor#62]
Refers to the documentation: https://moor.simonbinder.eu/queries/

I have a question about inserts.
In the documentation `Todo()` is used for creating the object.
```dart
Future<int> addTodoEntry(Todo entry) {
  return into(todos).insert(entry);
}

addTodoEntry(
  Todo(
    title: 'Important task',
    content: 'Refactor persistence code',
  ),
);
```
When I create an object without ID (`autoIncrement()` is used), the IDE (VSCode) will display a warning:
`The parameter 'id' is required.dart(missing_required_param)`.
It seems moor_generator also attaches `@required` to the ID, even though it is using `autoIncrement()`. Although this will not throw an error during runtime. When omitting other columns it will result in a runtime error.
Could this be changed to not display the warnings?

Also I noticed in your [gist](https://gist.github.com/simolus3/30f0b1fd6172384f3a77e6a03deea7bd) from before that you used a Companion also when inserting.
Should I also use Companion object when inserting? This would probably solve the warning problem mentioned above. Or should it only be used for updates?

Current `pubspec.lock`:
```yaml
moor:
  dependency: "direct overridden"
  description:
    path: "moor/"
    ref: develop
    resolved-ref: d98449407e1f170487fd0a1990d29d7b3ddeb93e
    url: "https://github.com/simolus3/moor.git"
  source: git
  version: "1.5.1+1"
moor_flutter:
  dependency: "direct main"
  description:
    name: moor_flutter
    url: "https://pub.dartlang.org"
  source: hosted
  version: "1.5.0"
moor_generator:
  dependency: "direct dev"
  description:
    name: moor_generator
    url: "https://pub.dartlang.org"
  source: hosted
  version: "1.5.0"
```

Thank you!
