### ISSUE TITLE
OrderBy returns no rows on Samsung S8 device

### ISSUE THREAD

**Issue by angel1st** [simolus3/moor#692]
This is the table definition I have got:
```
class Plants extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  DateTimeColumn get created => dateTime().withDefault(currentDateAndTime)();
  TextColumn get image => text().map(const ImageConverter()).nullable()();
  TextColumn get thumbnail => text().map(const ImageConverter()).nullable()();
}

```

this is **dao** file:

```
import 'package:moor/moor.dart';
import 'package:reminder/local_data_sources/plant_table.dart';
import 'app_database.dart';

part the 'plants_dao.g.dart';

@UseDao(tables: [Plants])
class PlantsDao extends DatabaseAccessor<AppDatabase> with _$PlantsDaoMixin {
  final AppDatabase db;
  PlantsDao(this.db) : super(db);

  Future<List<Plant>> getAll() => select(plants).get();
  Stream<List<Plant>> watchAll() => select(plants).watch();
  Stream<List<Plant>> watchAllOrderedByCreated() => (select(plants)
        ..orderBy(
          [(t) => OrderingTerm(expression: t.created, mode: OrderingMode.desc)],
        ))
      .watch();

  Future insertPlant(Insertable<Plant> plant) => into(plants).insert(plant);
  Future updatePlant(Insertable<Plant> plant) => update(plants).replace(plant);
  Future deletePlant(Insertable<Plant> plant) => delete(plants).delete(plant);
}

```
and this is how I call it:

```
  StreamBuilder<List<Plant>> _buildPlantsListInt(BuildContext context) {
    final PlantsDao plantsDao =
        RepositoryProvider.of<AppDatabase>(context).plantsDao;
    return StreamBuilder<List<Plant>>(
      stream: plantsDao.watchAllOrderedByCreated(),
      builder: (BuildContext context, AsyncSnapshot<List<Plant>> snapshot) {
        if (!snapshot.hasData) return _buildCircularProgressIndicator();
        final plants = snapshot.data;
        const int preferableBannerIndex = 6;
        int bannerIndex = plants.length > preferableBannerIndex
            ? preferableBannerIndex
            : plants.length;
        return ListView.builder(
          itemCount: plants.length + 1,
          itemBuilder: (_, index) {
            // if index is lower than bannerIndex
            if (index < bannerIndex) {
              return _buildListItem(plants[index], plantsDao);
            }
            // if index is equal to bannerIndex
            if (index == bannerIndex) {
              final AdMobRepository adMobRepository =
                  RepositoryProvider.of<AdMobRepository>(context);
              return adMobRepository.showBanner(
                context,
                AdmobBannerSize.BANNER,
              );
            }
            // if index is greater than bannerIndex
            if (index > bannerIndex) {
              return _buildListItem(plants[index - 1], plantsDao);
            }
            return Container();
          },
        );
      },
    );
  }

```

If I execute `watchAll()`, I have rows returned as they are. If, however, I execute `watchAllOrderedByCreated()` and there are more than one rows, the method hangs - basically, it doesn't return result - `snapshot.hasData` is always `false`.
The same code works just fine on Android emulator, which actually runs x86 image.

**Comment by simolus3** [comment]
Thanks for the report. Are you using `moor_ffi` or `moor_flutter`?

**Comment by angel1st** [comment]
moor_ffi 0.5.0. In fact I downgraded from 0.7.0, since I didnt able to
build release with 0.7.0

На пт, 10.07.2020 г., 18:03 ч. Simon Binder <notifications@github.com>
написа:

**Comment by angel1st** [comment]
This is my `pubspec.yaml` excerpt:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  shared_preferences: ^0.5.7+3
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker: ^0.3.4
  flutter_local_notifications: ^1.4.4+1
  flutter_svg: ^0.17.4
  admob_flutter: ^0.3.4
  image_picker: ^0.6.7+4
  moor: ^3.2.0
  moor_ffi: ^0.5.0
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  moor_generator: ^3.2.0
  build_runner:

```
