### ISSUE TITLE
Mutable option generates classes with const constructors without final fields

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#699]
Using this build.yaml:

```yaml
targets:
  $default:
    builders:
      moor_generator:
        options:
          generate_connect_constructor: true
          mutable_classes: true
```

Moor generates mutable classes (non final fields), but with const constructor (which are not allowed in Dart), resulting in a https://dart.dev/tools/diagnostic-messages#const_constructor_with_non_final_field

EDIT: It is hardcoded in https://github.com/simolus3/moor/blob/c80235799c445ffee8170748139538a981c9d66a/moor_generator/lib/src/writer/tables/update_companion_writer.dart#L40
