### ISSUE TITLE
.moor files outside of lib folder?

### ISSUE THREAD

**Issue by North101** [simolus3/moor#742]
Is there a way to have .moor files outside of of the lib folder?

I've tried:
`
@UseMoor(
  include: {
    './full/path/sql/file.moor',
    './sql/file.moor',
    '../sql/file.moor',
  }
)
`

**Comment by simolus3** [comment]
Yes, I think that should work, moor itself uses .moor files in `test/`. If you're running into issues, I assume that might be because the files aren't included in the default build inputs.

If they're not in common Dart directories like `lib/` or `test/`, you can create a `build.yaml` in your project dir with this content:

```yaml
targets:
  $default:
    sources:
     - moor/** # additional directory
     - lib/**  # default directories, see https://github.com/dart-lang/build/blob/cb74643ddf84565352912e5f9e90bf22fa74bfd3/build_runner_core/lib/src/generate/options.dart#L22-L37
     - test/**
     - pubspec.yaml
     - pubspec.lock
     - $package$
```
