### ISSUE TITLE
Moor Encryption package

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#758]
We are using your encryption implementation for our database.

The only problem we have is the installation. Right now we need to use a git url that can change at any time. It would be nice to have a package hosted on pub.dev. So we can make sure we are using the correct version. And we don't have to do extra tests fo make sure everything is working when something changes in this git directory

https://github.com/simolus3/moor/tree/master/extras/encryption

**Comment by davidmartos96** [comment]
If you worry about the repository updating, you can include a specific commit hash to your pubspec.yaml. Then you are in control on when to update the version. In any case, the moor `encryption` code is a quite simple file. 
https://github.com/simolus3/moor/blob/master/extras/encryption/lib/encrypted_moor.dart

```yaml
encrypted_moor:
   git:
    url: https://github.com/simolus3/moor.git
    path: extras/encryption
    ref: 5cbc331ddaf7a3031d98a905c2e05080d9fbb2c8
```

**Comment by vanlooverenkoen** [comment]
Fair point. 

Although I think should be available on pub.dev as well.

**Comment by simolus3** [comment]
I'm thinking about changing the encrypted moor package to bind to `SQLCipher` with `dart:ffi`.

Still needs a git dependency for now, but you can use it with

```yaml
dependencies:
  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs/
```

You can then use this to encrypt the database

```dart
VmDatabase(file, setup: (db) => db.execute("PRAGMA key = 'passphrase'"));
```

So far I didn't have the chance to fully test `sqlcipher_flutter_libs`, which is why it's not on pub yet. I hope I can release this soon though.
