### ISSUE TITLE
[Question] - How are the package releases build?

### ISSUE THREAD

**Issue by marcgraub** [simolus3/moor#820]
Hi! I have a project made with angular, and due it being dependant from analyzer 0.37.0, I'm stuck with moor 2.4.2 .

I need some functionalities from newer versions and I want to fork it and cherry pick some commits while I wait for angular to be updated, the problem is, I can't find a branch or state with all the functionalities from moor 2.4.2 .

So, my question is, how are the package releases build? And, where I can find the 2.4.2 state?

Thanks in advance for your attention to this question.

**Comment by simolus3** [comment]
> I can't find a branch or state with all the functionalities from moor 2.4.2 .

The latest commit of `2.4.2` was b2285e04ef17505381c043f303ae1cad16d96175, so you could branch from that.

> how are the package releases build

I'm not sure if I understand the question: The released packages are identical to the source here. You'll probably have to add `dependency_overrides` so that each project depends on the old local version:

```yaml
dependency_overrides:
  moor_generator:
    path: ../moor_generator
  sqlparser:
    path: ../sqlparser
  # ...
```
