### ISSUE TITLE
update to generate_values_in_copy_with

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#934]
I found out late that when I was updating with .copyWith(stuff: null) it wasn't doing actually anything.

So reading I see that you made some nice updates, like the option generate_values_in_copy_with.
Ok perfect, I updated moor from 3.0 to 3.4 and I set in `build.yaml` the option, and now the file looks like this:

```
targets:
  $default:
    builders:
      moor_generator:
        options:
          write_from_json_string_constructor: true
          mutable_classes: true
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
```
The rebuild at this point **doesn't** always built correctly, sometimes prompt an old friend error:
```
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
```

When it built correctly, I was hoping that replacing `null `with `Value(null)` was all, but now for all the other parameters I get:
`Error: The argument type 'String' can't be assigned to the parameter type 'Value<String>'.`
So, should I wrap **all** the other values in "Value()" (that is horrible) or I am missing something?

In which version did you added `generate_values_in_copy_with`?

In which version did you added `mutable_classes`?
( so maybe I will rollback to a previous version to avoid the InconsistentAnalysisException)

**Comment by simolus3** [comment]
>  So, should I wrap __all__ the other values in "Value()" (that is horrible) or I am missing something?

Unfortunately, you'll need to use `Value` for all nullable parameters. 

> `InconsistentAnalysisException: Requested result might be inconsistent with previously returned results`

Oh no. Does a `build_runner clean` help at all? `generate_values_in_copy_with` was added in 3.4, I don't really see how this would be related since it doesn't affect how we use the analyzer.

**Comment by apoleo88** [comment]
No, I use:
`flutter clean`
`build_runner clean`
also as option when I build  `--delete-conflicting-outputs`, but it doesn't fix the error.

Now I rolled back to 3.0(moor and builder), but somehow the error is following me, when I didn't had it before??


is `mutable_classes` available in 3.0?

**Comment by apoleo88** [comment]
Nothing the InconsistentAnalysisException still happens even on 3.0 now.
Invalidated the cache on my IDE, clean flutter and cleaned the build runner, nothing.

It is unbelievable how everytime I slighty touch this library it will stop working.

**Comment by kuhnroyal** [comment]
Try to compare your `pubspec.lock` and see if there are changes on `build_runner` and `analyzer` versions and possibly reset/freeze these. The problem is not moor but the dependencies on the Dart build tool chain that usually causes these problems.

3.4.0 works for me only with this combination currently:
```
dev_dependecies:
  build_runner: 1.10.2

dev_overrides:
  analyzer: 0.40.5
```

**Comment by apoleo88** [comment]
Thank you for the help.

I tried but I get this error:
```
Because build_runner 1.10.2 depends on build >=1.3.0 <1.4.0 and no versions of build match >1.3.0 <1.4.0, build_runner 1.10.2 requi
res build 1.3.0.
And because build 1.3.0 depends on analyzer >=0.35.0 <0.40.0 and moor_generator >=3.4.0 depends on analyzer ^0.40.0, build_runner 1
.10.2 is incompatible with moor_generator >=3.4.0.
So, because smartUser depends on both moor_generator ^3.4.0 and build_runner 1.10.2, version solving failed.

```
Also I am using:
`  moor_generator: ^3.4.0`

**Comment by kuhnroyal** [comment]
Seems you have `build: 1.3.0` declared? Try to remove this.

**Comment by apoleo88** [comment]
> Seems you have `build: 1.3.0` declared? Try to remove this.

I don't have anything like it in my `pubspec.yaml`

**Comment by kuhnroyal** [comment]
Can you show your pubspec?

**Comment by apoleo88** [comment]
```

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  moor: ^3.4.0
  sqlite3_flutter_libs:
  sqflite: ^1.1.7 # Still used to obtain the database location

  path_provider:
  path:
  provider: ^4.1.2
  shared_preferences:
  permission_handler:
  firebase_core:
  firebase_ml_vision: ^0.9.5
  firebase_database: ^4.0.0
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^7.0.2
  cloud_functions: ^0.6.0
  flutter_secure_storage: ^3.3.3
  google_sign_in: ^4.5.1
  firebase_auth: ^0.18.0+1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.4.0
  build_runner: 1.10.2

dev_overrides:
  analyzer: 0.40.5



```
