### ISSUE TITLE
Flutter Web with Firebase and Moor

### ISSUE THREAD

**Issue by mkiisoft** [simolus3/moor#94]
I simply can't install the library becase I keep getting the following error:

```
The current Dart SDK version is 2.4.0.                                  
                                                                        
Because moor_generator >=1.6.0+2 depends on analyzer >=0.36.0 <0.38.0 and build_modules ^1.0.7+2 depends on analyzer >0.30.0 <0.36.0, moor_generator >=1.6.0+2 is incompatible with build_modules ^1.0.7+2.
And because build_web_compilers >=0.4.4+1 <2.0.0-alpha.0 depends on build_modules >=0.4.0 <2.0.0, if moor_generator >=1.6.0+2 and build_web_compilers >=0.4.4+1 <2.0.0-alpha.0 then build_modules >=0.4.0 <=1.0.7+1.
Because build_modules >=0.3.0 <=1.0.7 depends on build_config >=0.2.1 <0.4.0 and build_modules >=1.0.7+1 <=1.0.7+1 requires SDK version 2.1.0, build_modules >=0.3.0 <=1.0.7+1 requires build_config >=0.2.1 <0.4.0.
Thus, if moor_generator >=1.6.0+2 and build_web_compilers >=0.4.4+1 <2.0.0-alpha.0 then build_config >=0.2.1 <0.4.0.
And because build_runner 1.6.5 depends on build_config >=0.4.1 <0.4.2, one of moor_generator >=1.6.0+2 or build_web_compilers >=0.4.4+1 <2.0.0-alpha.0 or build_runner 1.6.5 must be false.
And because no versions of build_runner match >1.6.5 <2.0.0 and omcadmin depends on build_runner ^1.6.5, moor_generator >=1.6.0+2 is incompatible with build_web_compilers >=0.4.4+1 <2.0.0-alpha.0.
So, because omcadmin depends on both build_web_compilers ^1.0.0 and moor_generator ^1.6.0+2, version solving failed.
```

Flutter doctor:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (1 available)
```

To keep using Firebase my build web compilers is the following:

`build_web_compilers: '>=1.0.0 <2.0.0'`

If not, I'll get a similar error.

YAML:

```
environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: any
  service_worker: ^0.2.3

dev_dependencies:
  build_runner: ^1.6.5
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.8.0+1
```
