### ISSUE TITLE
Support for null safety

### ISSUE THREAD

**Issue by noordawod** [simolus3/moor#964]
Hi, and thanks for the plugin!

I'm having trouble using the null-safe version of `sqflite` as `Moor` is still dependent on the previous iteration of the said plugin. 

Trying to use `sqflite 2.0.0-nullsafety.2` produces:

```text
$ flutter pub get
Running "flutter pub get" in example_app...

Because example_app depends on moor_flutter 3.1.0 which depends on sqflite ^1.1.6+5, sqflite ^1.1.6+5 is required.
So, because example_app depends on sqflite 2.0.0-nullsafety.2, version solving failed.
pub get failed (1; So, because example_app depends on sqflite 2.0.0-nullsafety.2, version solving failed.)
Process finished with exit code 1
```

Any plans to migrate to a null-safe Dart?

PS: null safety will be the default beyond 2020.

**Comment by simolus3** [comment]
I already started to migrate the moor packages, but I didn't want to publish them because I might want to introduce additional breaking changes.
I can release the null-safe versions to a personal pub server, that makes them a bit easier to use than with a git dependency override.

**Comment by simolus3** [comment]
I uploaded the current version of these packages to my pub server, you can use them like this:

```yaml
dependencies:
  moor:
    hosted:
      url: https://simonbinder.eu
      name: moor
    version: ^4.0.0-nullsafety
  moor_flutter:
    hosted:
      url: https://simonbinder.eu
      name: moor_flutter
    version: ^4.0.0-nullsafety

dev_dependencies:
  moor_generator:
    hosted:
      url: https://simonbinder.eu
      name: moor_generator
    version: ^4.0.0-dev
```

I'll keep this issue open until these packages are on the real pub.
