### ISSUE TITLE
Dart SDK version mismatch

### ISSUE THREAD

**Issue by bkekelic2** [simolus3/moor#999]
Hi, I have one question/ possible issue.

Recently I wanted to run `pug upgrade`, but came with an error which says that my current Dart SDK version is 2.10.4 and that encrypted_moor depends on >=2.12.0-0 <3.0.0.

As I can see from [official ](https://dart.dev/get-dart) documentation it says that versions 2.12 are beta versions or from dev channel. Also, in documentation it says that those channels are unstable, may be broken and should not be used for release.

So, my question is what should I do? Risk with Dart upgrade, or I'm missing something?
Thanks in advance.

**Comment by simolus3** [comment]
Apologies for the inconvenience.

You don't have to upgrade to Dart 2.12. You can keep using a version of `encrypted_moor` compatible with older Dart versions and moor 3.x. Just change the git ref to

```yaml
  encrypted_moor:
   git:
    url: https://github.com/simolus3/moor.git
    ref: 66a2cd0b09edd0280293eb8539c3d009aa17d42b
    path: extras/encryption 
```
